// ===============================================
// CONFIGURACIÓN MACRO (ARQUITECTURA)
// ===============================================
const CONFIG = {
    colores: {
        partidos: {
            "FUERZA POPULAR": "#F39C12",
            "RENOVACION POPULAR": "#2980B9",
            "PERU LIBRE": "#C0392B",
            "AHORA NACION - AN": "#8E44AD",
            "ALIANZA PARA EL PROGRESO": "#27AE60",
            "DEFECTO": "#95A5A6"
        }
    },
    filtros: {
        // Todo partido en esta lista será invisible en la web, pero seguirá existiendo en el JSON
        partidosOcultosVisualmente: [
            "PARTIDO CIUDADANOS POR EL PERU"
        ]
    },
    archivos: {
        masterJSON: "https://fabmonge.github.io/camaleones-politicos//Data_lista/candidatos_super_master.json",
        partidosJSON: "https://fabmonge.github.io/camaleones-politicos//Data_lista/diccionario_partidos.json" 
    },
    rutas: {
        baseFotos: "https://fabmonge.github.io/camaleones-politicos/fotos/",
    }
};

let todosLosCandidatos = [];
let diccionarioPartidos = {}; 
let timelineChartInstance = null; 

// ===============================================
// INYECCIÓN AUTOMÁTICA DE CSS (AJUSTES UI)
// ===============================================
const style = document.createElement('style');
style.innerHTML = `
/* Selectores Premium */
.custom-select-wrapper { position: relative; display: inline-block; user-select: none; font-family: inherit; vertical-align: middle; max-width: 100%; }
.custom-select-trigger { display: flex; align-items: center; justify-content: space-between; padding: 8px 12px; background-color: #fff; border: 1px solid #ccc; border-radius: 6px; cursor: pointer; font-size: 14px; color: #333; min-height: 38px; box-shadow: 0 1px 2px rgba(0,0,0,0.05); }
.custom-select-trigger .c-text { display: flex; align-items: center; font-weight: 500; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; }
.custom-select-trigger .c-arrow { font-size: 10px; color: #888; margin-left: 10px; flex-shrink: 0; }
.c-logo { width: 20px; height: 20px; object-fit: contain; margin-right: 8px; flex-shrink: 0; }
.c-icon-placeholder { width: 20px; height: 20px; margin-right: 8px; background: transparent; display: flex; align-items: center; justify-content: center; font-size: 11px; flex-shrink: 0; }
.custom-select-options { position: absolute; top: 100%; left: 0; right: 0; margin-top: 5px; background-color: #fff; border: 1px solid #ddd; border-radius: 6px; box-shadow: 0 4px 12px rgba(0,0,0,0.15); z-index: 999; max-height: 250px; overflow-y: auto; display: none; min-width: 100%; }
.custom-select-options.open { display: block; }
.custom-option { display: flex; align-items: center; padding: 10px 12px; cursor: pointer; font-size: 14px; border-bottom: 1px solid #f9f9f9; transition: background 0.2s; }
.custom-option:hover { background-color: #f1f1f1; }

/* Borde Gris Sutil y Eliminación de Anillos en Rankings */
.ranking-column { border-top: none !important; }
.chameleon-top { 
    border: 1px solid #e2e8f0 !important;
    border-radius: 8px !important;
    box-shadow: 0 2px 4px rgba(0,0,0,0.03) !important; 
    background-color: #fff !important;
    padding: 15px;
    margin-bottom: 12px;
}
.chameleon-top .photo, 
.chameleon-top .photo img {
    border: none !important;
    outline: none !important;
    box-shadow: none !important;
}

/* Escudo de Partido en el Avatar (Burbujas) */
.party-badge-mini {
    position: absolute;
    bottom: -4px;
    right: -4px;
    width: 35%;
    height: 35%;
    border-radius: 50%;
    border: 2px solid #fff;
    background-color: #fff;
    object-fit: contain;
    box-shadow: 0 2px 4px rgba(0,0,0,0.15);
    z-index: 5;
}


/* AJUSTE EDITORA: Reducir de 3 a 2 columnas para el Ranking */
/* AJUSTE EDITORA: Reducir de 3 a 2 columnas para el Ranking */
#rankings-wrapper {
    display: grid !important;
    grid-template-columns: repeat(2, 1fr) !important;
    gap: 30px !important;
    max-width: 800px !important;
    margin: 0 auto 30px auto !important;
}

/* Y EN CELULARES, LO BAJAMOS A 1 SOLA COLUMNA */
@media (max-width: 850px) {
    #rankings-wrapper {
        grid-template-columns: 1fr !important;
    }
}

/* Estructura para ordenar las camisetas en la tarjeta (Flex Wrap) */
.history-section { margin-top: 15px; width: 100%; }
.history-title { font-size: 12px; font-weight: bold; margin-bottom: 10px; color: #333; }
.jersey-track { display: flex; flex-wrap: wrap; gap: 10px; justify-content: center; width: 100%; }
.jersey-item { width: 65px; display: flex; flex-direction: column; align-items: center; text-align: center; }
.jersey-placeholder { width: 45px; height: 45px; position: relative; margin-bottom: 4px; border: none; background: transparent; }
.jersey-year { font-size: 11px; font-weight: bold; color: #111; }
.jersey-party-name { font-size: 9px; color: #666; line-height: 1.1; margin-top: 2px; width: 100%; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }
.jersey-role { font-size: 8px; color: #888; font-style: italic; margin-top: 2px; width: 100%; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
`;
document.head.appendChild(style);

// ===============================================
// UTILIDADES COMUNES
// ===============================================
const getInitials = (name) => {
    if (!name) return "?";
    let parts = name.split(' ').filter(n => n.length > 0);
    if(parts.length >= 2) return (parts[0][0] + parts[1][0]).toUpperCase();
    return parts[0] ? parts[0][0].toUpperCase() : "?";
};

const normalizarId = (str) => {
    if (!str) return "defecto";
    return str.toLowerCase()
              .normalize("NFD")
              .replace(/[\u0300-\u036f]/g, "")
              .replace(/[^a-z0-9]/g, '_')
              .replace(/_+/g, '_')
              .replace(/_$/g, '');
};

function hexToRgba(hex, alpha) {
    let c;
    if(/^#([A-Fa-f0-9]{3}){1,2}$/.test(hex)){
        c= hex.substring(1).split('');
        if(c.length== 3){
            c= [c[0], c[0], c[1], c[1], c[2], c[2]];
        }
        c= '0x'+c.join('');
        return 'rgba('+[(c>>16)&255, (c>>8)&255, c&255].join(',')+','+alpha+')';
    }
    return `rgba(149, 165, 166, ${alpha})`;
}

const getUrlImagen = (nombreArchivo) => {
    if (!nombreArchivo) return "";
    const tieneExtension = /\.(png|jpg|jpeg|webp)$/i.test(nombreArchivo);
    return `${CONFIG.rutas.baseFotos}${encodeURI(nombreArchivo)}${tieneExtension ? '' : '.png'}`;
};

const extraerAnioInicial = (anioStr) => {
    if (!anioStr) return 0;
    const match = String(anioStr).match(/\d{4}/);
    return match ? parseInt(match[0]) : 0;
};

const ensureArray = (data) => {
    if (!data || data === "NA") return [];
    let arr = Array.isArray(data) ? data : [data];
    return arr.filter(item => item && typeof item === 'object' && item.partido && String(item.partido).trim() !== "" && item.partido !== "NA");
};


// ===============================================
// DICCIONARIOS DE EQUIVALENCIA (CLONES Y ALIANZAS)
// ===============================================

const DICCIONARIO_CLONES = {
    "AGRUPACION INDEPENDIENTE AVANCEMOS": "CAMBIO RADICAL",
    "FRENTE POPULAR AGRICOLA FIA DEL PERU - FREPAP": "FRENTE POPULAR AGRICOLA FIA DEL PERU",
    "PARTIDO POLITICO PERU ACCION": "PERU NACION",
    "CAMBIO 90": "PERU PATRIA SEGURA",
    "PERUANOS POR EL KAMBIO": "PARTIDO POLÍTICO CONTIGO",
    "RESTAURACION NACIONAL": "VICTORIA NACIONAL",
    "SOLIDARIDAD NACIONAL": "RENOVACION POPULAR",
    "FUERZA 2011": "FUERZA POPULAR",
    "FUERZA 2011":"ALIANZA POR EL FUTURO",
    "FUERZA POPULAR":"ALIANZA POR EL FUTURO",
    "PODEMOS POR EL PROGRESO DEL PERU": "PODEMOS PERU",
    "ALIANZA PARA EL PROGRESO": "ALIANZA PARA EL PROGRESO DEL PERU",
    "PERU LIBERTARIO": "MOVIMIENTO POLITICO REGIONAL PERU LIBRE",
    "RENOVACION POPULAR": "SOLIDARIDAD NACIONAL",
    "ALIANZA SOLIDARIDAD NACIONAL":"SOLIDARIDAD NACIONAL",
    "PARTIDO POLITICO NACIONAL PERU LIBRE": "PERU LIBERTARIO",
    "PARTIDO DEMOCRATICO SOMOS PERU": "MOVIMIENTO INDEPENDIENTE SOMOS PERU - CAUSA DEMOCRATICA",
    "PARTIDO POLÍTICO CONTIGO": "PERUANOS POR EL KAMBIO",
    "UNION POR EL PERU": "AGRUPACION INDEPENDIENTE UNION POR EL PERU - SOCIAL DEMOCRACIA",
    "PARTIDO NACIONALISTA PERUANO": "GANA PERU",
    "ALIANZA ELECTORAL CAMBIO 90 - NUEVA MAYORIA": "ALIANZA POR EL FUTURO",
    "PARTIDO POPULAR CRISTIANO - PPC": "PARTIDO POPULAR CRISTIANO - PPC - UNIDAD NACIONAL",
    "IZQUIERDA UNIDA": "FRENTE ELECTORAL IZQUIERDA UNIDA",
    "CHIM PUM CALLAO": "CHIMPUM - CALLAO",
    "CHIMPUM CALLAO": "CHIM PUM CALLAO",
    "FRENTE NACIONAL DE TRABAJADORES Y CAMPESINOS": "PERU AL 2000 - FRENATRACA",
    // --- PARCHES DE NOMENCLATURA JNE ---
    "ALIANZA ELECTORAL UNIDAD NACIONAL": "UNIDAD NACIONAL",
    "PARTIDO POPULAR CRISTIANO": "PARTIDO POPULAR CRISTIANO - PPC",
    "ALIANZA ELECTORAL SOLIDARIDAD NACIONAL": "ALIANZA SOLIDARIDAD NACIONAL",
    "ALIANZA ELECTORAL IZQUIERDA UNIDA":"ALIANZA IZQUIERDA UNIDA"
};

const DICCIONARIO_ALIANZAS = {
    "ALIANZA SOLIDARIDAD NACIONAL": ["CAMBIO 90", "SIEMPRE UNIDOS", "UNION POR EL PERU", "TODOS POR EL PERU", "SOLIDARIDAD NACIONAL"],
    "PERÚ POSIBLE": ["PERU POSIBLE"],
    "ALIANZA POR EL GRAN CAMBIO": ["ALIANZA PARA EL PROGRESO", "RESTAURACION NACIONAL", "PARTIDO POPULAR CRISTIANO - PPC", "PARTIDO HUMANISTA PERUANO"],
    "ALIANZA POPULAR": ["PARTIDO APRISTA PERUANO", "PARTIDO POPULAR CRISTIANO - PPC", "VAMOS PERU"],
    "ALIANZA ELECTORAL SOLIDARIDAD NACIONAL - UPP": ["SOLIDARIDAD NACIONAL", "UNION POR EL PERU"],
    "ALIANZA PARA EL PROGRESO DE AREQUIPA": ["ALIANZA PARA EL PROGRESO"],
    "ALIANZA PARA EL PROGRESO DE AYACUCHO": ["ALIANZA PARA EL PROGRESO"],
    "ALIANZA PERU POSIBLE": ["ACCION POPULAR", "PARTIDO DEMOCRATICO SOMOS PERU", "PERU POSIBLE"],
    "SUMATE - PERU POSIBLE": ["PERU POSIBLE"],
    "UNIDAD NACIONAL": ["PARTIDO POPULAR CRISTIANO - PPC", "SOLIDARIDAD NACIONAL", "RENOVACION NACIONAL"],
    "FREDEMO": ["MOVIMIENTO LIBERTAD", "ACCION POPULAR", "PARTIDO POPULAR CRISTIANO", "PARTIDO SOLIDARIDAD Y DEMOCRACIA"],
    "FRENTE DE CENTRO": ["ACCION POPULAR", "PARTIDO DEMOCRATICO SOMOS PERU", "COORDINADORA NACIONAL DE INDEPENDIENTES"],
    "ALIANZA ELECTORAL PERU 2000": ["CAMBIO 90", "ALIANZA ELECTORAL VAMOS VECINO", "ALIANZA ELECTORAL CAMBIO 90 - NUEVA MAYORIA"],
    "ALIANZA ELECTORAL IZQUIERDA UNIDA": ["IZQUIERDA UNIDA"],
    "ALIANZA ELECTORAL SOLUCION POPULAR": ["ALIANZA ELECTORAL VAMOS VECINO"],
    "ALIANZA ELECTORAL VAMOS VECINO": ["ALIANZA ELECTORAL PERU 2000"],
    "ALIANZA ELECTORAL UNIDAD POPULAR": ["PARTIDO POPULAR CRISTIANO - PPC", "ALIANZA SOLIDARIDAD NACIONAL", "RENOVACION NACIONAL"],
    "CONVERGENCIA DEMOCRATICA": ["PARTIDO POPULAR CRISTIANO - PPC", "MOVIMIENTO DE BASES HAYISTAS"],
    "ALIANZA ELECTORAL IZQUIERDA UNIDA":["IZQUIERDA UNIDA", "FRENTE ELECTORAL IZQUIERDA UNIDA"],
};

// ===============================================
// DICCIONARIO DE NOMBRES CORTOS PARA DISPLAY (UI)
// ===============================================
const DICCIONARIO_NOMBRES_CORTOS = {
    "UNION REGIONAL": "UNION REGIONAL",
    "PARTIDO POLITICO ADP": "PARTIDO POLITICO ADP",
    "PARTIDO MORADO": "PARTIDO MORADO",
    "KAYPI PROGRESO": "KAYPI PROGRESO",
    "ALIANZA GOBIERNO UNIDAD Y ACCION - AGUA": "ALIANZA GOBIERNO UNIDAD Y ACCION - AGUA",
    "REFORMA Y HONRADEZ POR MAS OBRAS": "REFORMA Y HONRADEZ POR MAS OBRAS",
    "NUEVA MAYORIA": "NUEVA MAYORIA",
    "CAMBIO RADICAL": "CAMBIO RADICAL",
    "PARTIDO DESCENTRALISTA FUERZA SOCIAL": "FUERZA SOCIAL",
    "FUERZA NACIONAL": "FUERZA NACIONAL",
    "PARTIDO POLITICO ADELANTE": "PARTIDO POLITICO ADELANTE",
    "FRENTE POPULAR AGRICOLA FIA DEL PERU": "FREPAP",
    "CONCERTACION DESCENTRALISTA": "CONCERTACION DESCENTRALISTA",
    "FONAVISTAS DEL PERU": "FONAVISTAS DEL PERU",
    "BLOQUE POPULAR JUNIN": "BLOQUE POPULAR JUNIN",
    "MOVIMIENTO REGIONAL TUMBES UNIDO": "TUMBES UNIDO",
    "PROGRESEMOS": "PROGRESEMOS",
    "NUEVO PERU POR EL BUEN VIVIR": "NUEVO PERÚ",
    "MOVIMIENTO LISTA DE INTEGRACION PARA EL DESARROLLO REGIONAL": "LISTA DE INTEGRACION PARA EL DESARROLLO REGIONAL",
    "MOVIMIENTO REGIONAL FORTALEZA PERU": "FORTALEZA PERÚ",
    "MOVIMIENTO INDEPENDIENTE REGIONAL FUERZA TACNA": "FUERZA TACNA",
    "ACCION POPULAR": "ACCION POPULAR",
    "ALIANZA SOLIDARIDAD NACIONAL": "ALIANZA SOLIDARIDAD NACIONAL",
    "PERÚ POSIBLE": "PERÚ POSIBLE",
    "ALIANZA POR EL GRAN CAMBIO": "ALIANZA POR EL GRAN CAMBIO",
    "ALTERNATIVA LIBRE": "ALTERNATIVA LIBRE",
    "ORGANIZACION INDEPENDIENTE ASHANINKA DEL PICHIS": "ORGANIZACION INDEPENDIENTE ASHANINKA DEL PICHIS",
    "UNIDOS PUEBLO AGRO TAMBOGRANDE CASERIOS UNIDOS": "UPA-TCU",
    "DIGNIDAD VECINAL": "DIGNIDAD VECINAL",
    "UNIDOS POR EL CAMBIO DE PACHANGARA": "UNIDOS POR EL CAMBIO DE PACHANGARA",
    "ACCION SOLIDARIA": "ACCION SOLIDARIA",
    "RESURGIR SALPINO": "RESURGIR SALPINO",
    "ARMANDO EL PROGRESO": "ARMANDO EL PROGRESO",
    "ORGANIZACION POLITICA INDEPENDIENTE DISTRITAL ALTERNATIVA VERDE": "ALTERNATIVA VERDE",
    "¡ARRIBA PAIJAN!": "ARRIBA PAIJAN",
    "CONTIGO LAREDO": "CONTIGO LAREDO",
    "IZQUIERDA PAMPINA": "IZQUIERDA PAMPINA",
    "PASCO VERDE": "PASCO VERDE",
    "PRIMERO LA GENTE - COMUNIDAD, ECOLOGIA, LIBERTAD Y PROGRESO": "PRIMERO LA GENTE",
    "MOVIMIENTO DE INCLUSION REGIONAL": "MOVIMIENTO DE INCLUSION REGIONAL",
    "MOVIMIENTO REGIONAL AYNI": "AYNI",
    "MOVIMIENTO INDEPENDIENTE REGIONAL MI BUEN VECINO": "MI BUEN VECINO",
    "UNO POR ICA": "UNO POR ICA",
    "SOCIOS POR ANCASH": "SOCIOS POR ANCASH",
    "PERU MODERNO": "PERU MODERNO",
    "PERU NACION": "PERU NACION",
    "VAMOS PERU": "VAMOS PERU",
    "PERU PATRIA SEGURA": "PERU PATRIA SEGURA",
    "DEMOCRACIA DIRECTA": "DEMOCRACIA DIRECTA",
    "TODOS POR EL PERU": "TODOS POR EL PERU",
    "PARTIDO POLITICO CONTIGO": "CONTIGO",
    "VICTORIA NACIONAL": "VICTORIA NACIONAL",
    "EL FRENTE AMPLIO POR JUSTICIA, VIDA Y LIBERTAD": "FRENE AMPLIO",
    "RENACIMIENTO UNIDO NACIONAL": "RENACIMIENTO UNIDO NACIONAL",
    "PARTIDO NACIONALISTA PERUANO": "PARTIDO NACIONALISTA PERUANO",
    "UNION POR EL PERU": "UNION POR EL PERU",
    "FRENTE REGIONAL DE CAJAMARCA": "FRENTE REGIONAL DE CAJAMARCA",
    "RENOVACION POPULAR": "RENOVACION POPULAR",
    "MOVIMIENTO ESPERANZA REGION AMAZONICA": "ESPERANZA REGION AMAZONICA",
    "MOVIMIENTO POLITICO REGIONAL DIGNIDAD TUMBESINA": "DIGNIDAD TUMBESINA",
    "FUERZA AREQUIPEÑA": "FUERZA AREQUIPEÑA",
    "REGION PARA TODOS": "REGION PARA TODOS",
    "CAJAMARCA SIEMPRE VERDE": "CAJAMARCA SIEMPRE VERDE",
    "LIBERTAD POPULAR": "LIBERTAD POPULAR",
    "FUERZA POPULAR": "FUERZA POPULAR",
    "MOVIMIENTO DE INTEGRACION Y REVOLUCION ANDINA": "MOVIMIENTO DE INTEGRACION Y REVOLUCION ANDINA",
    "MOVIMIENTO REGIONAL QATARY HUANCAVELICA": "QATARY HUANCAVELICA",
    "ALIANZA POPULAR": "ALIANZA POPULAR",
    "HATARIY APURIMAC": "HATARIY APURIMAC",
    "MOVIMIENTO REGIONAL WARI LLAQTA": "WARI LLAQTA",
    "PODEMOS PERU": "PODEMOS PERU",
    "JUNIN RENACE": "JUNIN RENACE",
    "PARTIDO POPULAR CRISTIANO - PPC": "PPC",
    "MOVIMIENTO REGIONAL INKA PACHAKUTEQ": "INKA PACHAKUTEQ",
    "ORGANIZACION POLITICA UNIDAD REGIONAL": "UNIDAD REGIONAL",
    "LA PERLA EMPRENDE, SI SE PUEDE": "LA PERLA EMPRENDE, SI SE PUEDE",
    "POR UN SAN JUAN SEGURO": "POR UN SAN JUAN SEGURO",
    "MOVIMIENTO INDEPENDIENTE TAMBOGRANDINO": "MOV. INDEPENDIENTE TAMBOGRANDINO",
    "AGROPECUARIO HONORIA PROGRESO": "AGROPECUARIO HONORIA PROGRESO",
    "TRABAJO + TRABAJO": "TRABAJO + TRABAJO",
    "PODER Y CAMBIO AL 2010": "PODER Y CAMBIO AL 2010",
    "UPA-TCU UNIDOS PUEBLO AGRO TAMBOGRANDE CASERIOS UNIDOS": "UPA-TCU",
    "LOS INDEPENDIENTES": "LOS INDEPENDIENTES",
    "TE QUIERO WANCHAQ": "TE QUIERO WANCHAQ",
    "TRABAJO MAS TRABAJO": "TRABAJO MAS TRABAJO",
    "FRENTE DE INTEGRACION VECINAL DE UTCUBAMBA": "FRENTE DE INTEGRACION VECINAL DE UTCUBAMBA",
    "ORGANIZACION INDEPENDIENTE TODOS POR ILO": "TODOS POR ILO",
    "NUEVO SATIPO": "NUEVO SATIPO",
    "ALIANZA PARA EL PROGRESO": "APP",
    "SECHURANOS UNIDOS": "SECHURANOS UNIDOS",
    "CAMINEMOS JUNTOS POR JUNIN": "CAMINEMOS JUNTOS POR JUNIN",
    "VALE ANCASH": "VALE ANCASH",
    "DIALOGO VECINAL": "DIALOGO VECINAL",
    "LINDO HUARMEY": "LINDO HUARMEY",
    "DIGNIDAD Y ESPERANZA FERREÑAFANA": "DIGNIDAD Y ESPERANZA FERREÑAFANA",
    "CUSCO LINDO": "CUSCO LINDO",
    "ESPERANZA CIUDADANA": "ESPERANZA CIUDADANA",
    "MOVIMIENTO VERDE DE UCAYALI": "MOVIMIENTO VERDE DE UCAYALI",
    "PARTIDO DEMOCRATA UNIDO PERU": "PARTIDO DEMOCRATA UNIDO PERU",
    "TODOS SOMOS UCAYALI": "TODOS SOMOS UCAYALI",
    "PROGRESANDO PERU": "PROGRESANDO PERU",
    "FRENTE ESPERANZA": "FRENTE ESPERANZA",
    "PARTIDO POLITICO ORDEN": "ORDEN",
    "PERU POSIBLE": "PERU POSIBLE",
    "MOVIMIENTO REGIONAL MAS CALLAO": "MAS CALLAO",
    "PARTIDO DEMOCRATA VERDE": "PARTIDO DEMOCRATA VERDE",
    "FE EN EL PERU": "FE EN EL PERU",
    "MOVIMIENTO REGIONAL BICENTENARIO - LA LIBERTAD": "BICENTENARIO - LA LIBERTAD",
    "ALIANZA REGIONAL TODOS POR PASCO": "TODOS POR PASCO",
    "MOVIMIENTO REGIONAL AGUA": "MOV. REGIONAL AGUA",
    "MOVIMIENTO ACCION NACIONALISTA PERUANO": "ACCION NACIONALISTA PERUANO",
    "PARTIDO POLITICO NACIONAL PERU LIBRE": "PERU LIBRE",
    "MOVIMIENTO REGIONAL VIVA TACNA": "MOVIMIENTO REGIONAL VIVA TACNA",
    "IGUALDAD NACIONAL CRISTIANA AUTONOMA - INCA": "IGUALDAD NACIONAL CRISTIANA AUTONOMA",
    "MOVIMIENTO INDEPENDIENTE REGIONAL FAENA": "FAENA",
    "INTEGRACION Y DESARROLLO": "INTEGRACION Y DESARROLLO",
    "JUNTOS POR LORETO": "JUNTOS POR LORETO",
    "MOVIMIENTO REGIONAL TUMBES DECIDE": "TUMBES DECIDE",
    "UNIDAD, EXPERIENCIA Y TRABAJO CON ETICA": "UNIDAD, EXPERIENCIA Y TRABAJO CON ETICA",
    "MOVIMIENTO REGIONAL FUTURO Y PROGRESO JUNIN": "FUTURO Y PROGRESO JUNIN",
    "MOVIMIENTO INDEPENDIENTE LORETO - MI LORETO": "MI LORETO",
    "MISION ORGANIZADA VIA INTEGRIDAD Y LIBERTAD": "MISION ORGANIZADA VIA INTEGRIDAD Y LIBERTAD",
    "MOVIMIENTO REGIONAL BLOQUE POPULAR JUNIN": "BLOQUE POPULAR JUNIN",
    "SUMATE": "SUMATE",
    "MOVIMIENTO VERDE UNIDO": "MOVIMIENTO VERDE UNIDO",
    "MOVIMIENTO LIDER  - LISTA DE INTEGRACION PARA EL DESARROLLO REGIONAL": "MOVIMIENTO LIDER",
    "FUERZA LORETANA": "FUERZA LORETANA",
    "SI SE PUEDE": "SI SE PUEDE",
    "FUERZA REGIONAL": "FUERZA REGIONAL",
    "FRENTE DE INTEGRACION REGIONAL MOQUEGUA EMPRENDEDORA FIRME": "MOQUEGUA EMPRENDEDORA FIRME",
    "ARRIBA TACNA": "ARRIBA TACNA",
    "MOVIMIENTO INTEGRACION LORETANA": "INTEGRACION LORETANA",
    "NUEVA AMAZONIA": "NUEVA AMAZONIA",
    "NUEVA LIBERTAD": "NUEVA LIBERTAD",
    "REFORMA Y HONRADEZ": "REFORMA Y HONRADEZ",
    "AREQUIPA - UNIDOS POR EL GRAN CAMBIO": "AREQUIPA - UNIDOS POR EL GRAN CAMBIO",
    "MOVIMIENTO REGIONAL LLANKASUN KUSKA": "LLANKASUN KUSKA",
    "JUNIN SOSTENIBLE CON SU GENTE": "JUNIN SOSTENIBLE CON SU GENTE",
    "MOVIMIENTO REGIONAL FUERZA AMAZONENSE": "FUERZA AMAZONENSE",
    "MOVIMIENTO REGIONAL VIVA EL CALLAO": "VIVA EL CALLAO",
    "ACCION REGIONAL": "ACCION REGIONAL",
    "FRENTE INDEPENDIENTE ALIANZA REGIONAL F.I.A.R.- \"NUEVA GENERACION \"": "F.I.A.R.- NUEVA GENERACION",
    "ALIANZA RENACE AYACUCHO": "RENACE AYACUCHO",
    "MOVIMIENTO REGIONAL TAWANTINSUYO": "MOV. REGIONAL TAWANTINSUYO",
    "COMBINA JUNIN": "COMBINA JUNIN",
    "MOVIMIENTO DE DESARROLLO LOCAL MODELO REGION PIURA": "MOVIMIENTO DE DESARROLLO LOCAL MODELO REGION PIURA",
    "GRAN PROYECTO SOCIAL": "GRAN PROYECTO SOCIAL",
    "AUTOGOBIERNO AYLLU": "AUTOGOBIERNO AYLLU",
    "CORAZON PATRIOTA": "CORAZON PATRIOTA",
    "TODOS POR EL GRAN CAMBIO": "TODOS POR EL GRAN CAMBIO",
    "IDENTIDAD REGIONAL": "IDENTIDAD REGIONAL",
    "AREQUIPA RENACE": "AREQUIPA RENACE",
    "KAUSACHUN CUSCO": "KAUSACHUN CUSCO",
    "MOVIMIENTO REGIONAL REVALORA": "MOV. REGIONAL REVALORA",
    "OBRAS POR AMAZONAS": "OBRAS POR AMAZONAS",
    "DESARROLLO INTEGRAL AYACUCHO": "DESARROLLO INTEGRAL AYACUCHO",
    "FRENTE AMPLIO PARA EL DESARROLLO DEL PUEBLO": "FRENTE AMPLIO PARA EL DESARROLLO DEL PUEBLO",
    "MOVIMIENTO DE AFIRMACION SOCIAL": "MOVIMIENTO DE AFIRMACION SOCIAL",
    "MOVIMIENTO REGIONAL FUERZA SOCIAL CAJAMARCA": "FUERZA SOCIAL CAJAMARCA",
    "MOVIMIENTO REGIONAL SOMOS CALLAO": "SOMOS CALLAO",
    "QATUN TARPUY": "QATUN TARPUY",
    "AREQUIPA TRANSFORMACION": "AREQUIPA TRANSFORMACION",
    "MOVIMIENTO INDEPENDIENTE CHIMPUM CALLAO": "CHIMPUM CALLAO",
    "UNION DEMOCRATICA DEL NORTE": "UNION DEMOCRATICA DEL NORTE",
    "AVANZADA REGIONAL INDEPENDIENTE UNIDOS POR HUANUCO": "UNIDOS POR HUANUCO",
    "MOVIMIENTO INDEPENDIENTE REGIONAL RIO SANTA CAUDALOSO": "RIO SANTA CAUDALOSO",
    "FRENTE ANDINO AMAZONICO": "FRENTE ANDINO AMAZONICO",
    "JUNTOS POR EL DESARROLLO DE AREQUIPA": "JUNTOS POR EL DESARROLLO DE AREQUIPA",
    "MOVIMIENTO DE INTEGRACION POR EL DESARROLLO REGIONAL (MI CASITA)": "MI CASITA",
    "MOVIMIENTO POPULAR KALLPA": "MOVIMIENTO POPULAR KALLPA",
    "MOVIMIENTO INDEPENDIENTE REGIONAL ANCASH A LA OBRA": "ANCASH A LA OBRA",
    "MOVIMIENTO INDEPENDIENTE REGIONAL UNIDOS POR HUANCAVELICA": "UNIDOS POR HUANCAVELICA",
    "CONCERTACION EN LA REGION": "CONCERTACION EN LA REGION",
    "PARTIDO REGIONAL DE INTEGRACION": "PARTIDO REGIONAL DE INTEGRACION",
    "MOVIMIENTO INDEPENDIENTE DE CAMPESINOS Y PROFESIONALES": "MOVIMIENTO INDEPENDIENTE DE CAMPESINOS Y PROFESIONALES",
    "POR TI CALLAO": "POR TI CALLAO",
    "NUESTRO ILO - MOQUEGUA - SANCHEZ CERRO": "NUESTRO ILO - MOQUEGUA - SANCHEZ CERRO",
    "UNIDOS POR LA REGION": "UNIDOS POR LA REGION",
    "FUERZA CALLAO SEGURO": "FUERZA CALLAO SEGURO",
    "MOVIMIENTO REGIONAL SEGURIDAD Y PROSPERIDAD": "SEGURIDAD Y PROSPERIDAD",
    "MOVIMIENTO DE IDENTIDAD REGIONAL DE AYACUCHO": "MOVIMIENTO DE IDENTIDAD REGIONAL DE AYACUCHO",
    "UDC CALLAO": "UDC CALLAO",
    "MUSUQ ÑAN": "MUSUQ ÑAN",
    "FRENTE REGIONAL AYACUCHO": "FRENTE REGIONAL AYACUCHO",
    "ALIANZA ELECTORAL SOLIDARIDAD NACIONAL - UPP": "ALIANZA SOLIDARIDAD NACIONAL - UPP",
    "PARTIDO FRENTE DE LA ESPERANZA 2021": "FRENTE DE LA ESPERANZA",
    "PARTIDO MOVIMIENTO HUMANISTA PERUANO": "PARTIDO HUMANISTA PERUANO",
    "CONCERTACION PARA EL DESARROLLO REGIONAL - LIMA": "CONCERTACION PARA EL DESARROLLO REGIONAL - LIMA",
    "RECUPEREMOS TACNA": "RECUPEREMOS TACNA",
    "MOVIMIENTO REGIONAL PROGRESO Y DESARROLLO": "PROGRESO Y DESARROLLO",
    "MOVIMIENTO TUMBESINO PUEBLO UNIDO": "MOVIMIENTO TUMBESINO PUEBLO UNIDO",
    "FUERZA TUMBESINA 2010": "FUERZA TUMBESINA 2010",
    "MI CALLAO": "MI CALLAO",
    "CONVERGENCIA REGIONAL DESCENTRALISTA": "CONVERGENCIA REGIONAL DESCENTRALISTA",
    "FRENTE REGIONAL UNIDOS POR TACNA": "UNIDOS POR TACNA",
    "MOVIMIENTO REGIONAL AREQUIPA CUENTA CONMIGO": "AREQUIPA CUENTA CONMIGO",
    "REFORMA REGIONAL ANDINA INTEGRACION, PARTICIPACION ECONOMICA Y SOCIAL PUNO": "REFORMA REGIONAL ANDINA INTEGRACION, PARTICIPACION ECONOMICA Y SOCIAL PUNO",
    "INTEGRACION REGIONAL POR TI": "INTEGRACION REGIONAL POR TI",
    "MOVIMIENTO REGIONAL OBRAS + OBRAS": "OBRAS + OBRAS",
    "MOVIMIENTO POLITICO REGIONAL FUERZA JUVENIL": "FUERZA JUVENIL",
    "POR TODOS": "POR TODOS",
    "UNIDOS CONSTRUYENDO": "UNIDOS CONSTRUYENDO",
    "MOVIMIENTO REGIONAL INDEPENDIENTE CUENTA CONMIGO": "CUENTA CONMIGO",
    "VAMOS AREQUIPA": "VAMOS AREQUIPA",
    "MOVIMIENTO REGIONAL PAN": "MOV. REGIONAL PAN",
    "MOVIMIENTO POPULAR AYMARA QUECHUA AMAZONENSE": "AYMARA QUECHUA AMAZONENSE",
    "MOVIMIENTO DE INTEGRACION ECOLOGISTA TUMBESINO": "MOV. DE INTEGRACION ECOLOGISTA TUMBESINO",
    "PUERTO CALLAO": "PUERTO CALLAO",
    "TACNA EN ACCION": "TACNA EN ACCION",
    "PROYECTO POLITICO AQUI": "PROYECTO POLITICO AQUI",
    "BLOQUE POPULAR UCAYALI": "BLOQUE POPULAR UCAYALI",
    "FRENTE POPULAR LLAPANCHIK": "FRENTE POPULAR LLAPANCHIK",
    "TIERRA Y LIBERTAD CUSCO": "TIERRA Y LIBERTAD CUSCO",
    "FRENTE DEMOCRATICO REGIONAL": "FRENTE DEMOCRATICO REGIONAL",
    "POR LA UNIDAD Y LA MODERNIDAD DE JUNIN VENCEREMOS": "POR LA UNIDAD Y LA MODERNIDAD DE JUNIN VENCEREMOS",
    "FRENTE REGIONAL PODER COMUNAL": "PODER COMUNAL",
    "MOVIMIENTO REGIONAL DE MADRE DE DIOS MINEROS UNIDOS": "MINEROS UNIDOS",
    "BLOQUE POPULAR MADRE DE DIOS": "BLOQUE POPULAR MADRE DE DIOS",
    "PARTICIPACION TUMBESINA": "PARTICIPACION TUMBESINA",
    "MOVIMIENTO POLITICO REGIONAL UNIPOL": "UNIPOL",
    "AGRO SI": "AGRO SI",
    "MOVIMIENTO POLITICO REGIONAL VAMOS TACNA": "VAMOS TACNA",
    "MOVIMIENTO ETNOCACERISTA AYACUCHO": "MOVIMIENTO ETNOCACERISTA AYACUCHO",
    "COLECTIVO CIUDADANO CONFIANZA PERU": "COLECTIVO CIUDADANO CONFIANZA PERU",
    "LUCHEMOS POR TUMBES": "LUCHEMOS POR TUMBES",
    "ADUANEC": "ADUANEC",
    "MOVIMIENTO AMPLIO REGIONAL CALLAO": "MOVIMIENTO AMPLIO REGIONAL CALLAO",
    "ALIANZA PARA EL PROGRESO DE AREQUIPA": "ALIANZA PARA EL PROGRESO DE AREQUIPA",
    "CONCERTACION EN PRO DE UNA MISION SOSTENIBLE": "CONCERTACION EN PRO DE UNA MISION SOSTENIBLE",
    "PROYECTO INTEGRACIONISTA DE COMUNIDADES ORGANIZADAS": "PROYECTO INTEGRACIONISTA DE COMUNIDADES ORGANIZADAS",
    "LORETO PARA TODOS": "LORETO PARA TODOS",
    "INTEGRANDO UCAYALI": "INTEGRANDO UCAYALI",
    "PATRIA ARRIBA PERU ADELANTE": "PATRIA ARRIBA PERU ADELANTE",
    "ALIANZA NACIONAL DE TRABAJADORES AGRICULTORES UNIVERSITARIOS RESERVISTAS Y OBREROS": "ANTAURO",
    "MOVIMIENTO REGIONAL NUEVA LIBERTAD": "NUEVA LIBERTAD",
    "PARTIDO POLITICO PRIN": "PRIN",
    "PARTIDO RENACIMIENTO ANDINO": "RENACIMIENTO ANDINO",
    "PARTIDO POLITICO PERU PRIMERO": "PERU PRIMERO",
    "MOVIMIENTO POLITICO REGIONAL PERU LIBRE": "MOVIMIENTO POLITICO REGIONAL PERU LIBRE",
    "UNION CARRIONINA": "UNION CARRIONINA",
    "SENTIMIENTO AMAZONENSE REGIONAL": "SENTIMIENTO AMAZONENSE REGIONAL",
    "OBRAS SIEMPRE OBRAS": "OBRAS SIEMPRE OBRAS",
    "ALIANZA PARA EL PROGRESO DE AYACUCHO": "ALIANZA PARA EL PROGRESO DE AYACUCHO",
    "COALICION TRANSFORMADORA TIERRA VERDE": "COALICION TRANSFORMADORA TIERRA VERDE",
    "FUTURO PARA TODOS": "FUTURO PARA TODOS",
    "DEMOCRACIA CON VALORES": "DEMOCRACIA CON VALORES",
    "PATRIA JOVEN": "PATRIA JOVEN",
    "UCAYALI REGION CON FUTURO": "UCAYALI REGION CON FUTURO",
    "PARTIDO DEMOCRATICO SOMOS PERU": "SOMOS PERU",
    "JUNTOS POR EL PERU": "JUNTOS POR EL PERU",
    "ALIANZA PERU POSIBLE": "ALIANZA PERU POSIBLE",
    "GRAN ALIANZA NACIONALISTA DE MADRE DE DIOS": "GRAN ALIANZA NACIONALISTA DE MADRE DE DIOS",
    "ACUERDO REGIONAL DE INTEGRACION": "ACUERDO REGIONAL DE INTEGRACION",
    "SUMATE - PERU POSIBLE": "SUMATE - PERU POSIBLE",
    "PARTIDO APRISTA PERUANO": "APRA",
    "BANDERAS TACNEÑISTAS": "BANDERAS TACNEÑISTAS",
    "AHORA NACION - AN": "AHORA NACION",
    "VIVA PUNO": "VIVA PUNO",
    "MOVIMIENTO REGIONAL UNIDAD CIVICA LIMA": "UNIDAD CIVICA LIMA",
    "NUEVA ESPERANZA": "NUEVA ESPERANZA",
    "ALIANZA POR NUESTRO DESARROLLO": "ALIANZA POR NUESTRO DESARROLLO",
    "ALIANZA REGIONAL JUNTOS POR AMAZONAS": "ALIANZA JUNTOS POR AMAZONAS",
    "PARTIDO POLITICO PERU ACCION": "PERU ACCION",
    "MOVIMIENTO REGIONAL OBRAS POR LA MODERNIDAD": "OBRAS POR LA MODERNIDAD",
    "AREQUIPA, TRADICION Y FUTURO": "AREQUIPA, TRADICION Y FUTURO",
    "SOMOS PUEBLO": "SOMOS PUEBLO",
    "MOVIMIENTO INDEPENDIENTE POLITICO VOLUNTAD GENERAL AMAZONICA - VOGA": "VOLUNTAD GENERAL AMAZONICA",
    "PROGRESISTA DE APURIMAC": "PROGRESISTA DE APURIMAC",
    "AVANZA PAIS - PARTIDO DE INTEGRACION SOCIAL": "AVANZA PAIS",
    "PARTIDO RECONSTRUCCION DEMOCRATICA": "PARTIDO RECONSTRUCCION DEMOCRATICA",
    "PROYECTO PAIS": "PROYECTO PAIS",
    "Y SE LLAMA PERU": "Y SE LLAMA PERU",
    "FUERZA DEMOCRATICA": "FUERZA DEMOCRATICA",
    "PARTIDO SOCIALISTA": "PARTIDO SOCIALISTA",
    "RESURGIMIENTO PERUANO": "RESURGIMIENTO PERUANO",
    "FRENTE INDEPENDIENTE MORALIZADOR": "FRENTE INDEPENDIENTE MORALIZADOR",
    "PERU AHORA": "PERU AHORA",
    "PARTIDO POR LA DEMOCRACIA SOCIAL - COMPROMISO PERU": "PARTIDO POR LA DEMOCRACIA SOCIAL - COMPROMISO PERU",
    "CON FUERZA PERU": "CON FUERZA PERU",
    "PARTIDO JUSTICIA NACIONAL": "PARTIDO JUSTICIA NACIONAL",
    "FRENTE POPULAR AGRICOLA FIA DEL PERU - FREPAP": "FREPAP",
    "AREQUIPA REVOLUCION E IGUALDAD": "AREQUIPA REVOLUCION E IGUALDAD",
    "RENOVACION POR EL DESARROLLO": "RENOVACION POR EL DESARROLLO",
    "ALLIN KAUSAY": "ALLIN KAUSAY",
    "MOVIMIENTO INDEPENDIENTE REGIONAL INTI": "MOV. REGIONAL INTI",
    "MOVIMIENTO POR LA AUTONOMIA REGIONAL QUECHUA-AYMARA": "MOVIMIENTO POR LA AUTONOMIA REGIONAL QUECHUA-AYMARA",
    "ESFUERZO UNIDOS": "ESFUERZO UNIDOS",
    "FUERZA UNIDAD MOQUEGUA": "FUERZA UNIDAD MOQUEGUA",
    "MOVIMIENTO REGIONAL VOZ VERDE": "VOZ VERDE",
    "MOVIMIENTO INDEPENDIENTE NUEVA ESPERANZA REGIONAL ANCASHINA \"NUEVA ERA\"": "NUEVA ESPERANZA REGIONAL ANCASHINA",
    "MOVIMIENTO DE INNOVACION CAJAMARCA": "MOVIMIENTO DE INNOVACION CAJAMARCA",
    "FUERZA REGIONAL INKA": "FUERZA REGIONAL INKA",
    "MOVIMIENTO DEMOCRATICO JUNTOS POR EL PROGRESO": "JUNTOS POR EL PROGRESO",
    "FRENTE INDEPENDIENTE DE LORETO": "FRENTE INDEPENDIENTE DE LORETO",
    "FRENTE INDEPENDIENTE REGIONAL": "FRENTE INDEPENDIENTE REGIONAL",
    "MOVIMIENTO POLITICO REGIONAL IDEAS": "IDEAS",
    "QOSQOLLAY": "QOSQOLLAY",
    "REVOLUCION REGIONAL": "REVOLUCION REGIONAL",
    "MOVIMIENTO REGIONAL FUERZA POR MADRE DE DIOS - MR FMDD": "FUERZA POR MADRE DE DIOS",
    "MOVIMIENTO INDEPENDIENTE REGIONAL CAMBIO UCAYALINO": "CAMBIO UCAYALINO",
    "TODOS SOMOS AMAZONAS": "TODOS SOMOS AMAZONAS",
    "EL AGRO A LA REGION": "EL AGRO A LA REGION",
    "TIERRA Y LIBERTAD": "TIERRA Y LIBERTAD",
    "UNIDOS POR CHINCHA": "UNIDOS POR CHINCHA",
    "ACCION POR EL BIENESTAR": "ACCION POR EL BIENESTAR",
    "FRENTE METROPOLITANO": "FRENTE METROPOLITANO",
    "ROCA FUERTE - SEGUNDA JERUSALEN": "ROCA FUERTE - SEGUNDA JERUSALEN",
    "MOVIMIENTO INDEPENDIENTE REGIONAL YO SI AMO A TUMBES": "YO SI AMO A TUMBES",
    "MOVIMIENTO INDEPENDIENTE INNOVACION REGIONAL": "INNOVACION REGIONAL",
    "MOVIMIENTO REGIONAL ACUERDO POPULAR UNIFICADO": "ACUERDO POPULAR UNIFICADO",
    "JUNTOS POR EL SUR": "JUNTOS POR EL SUR",
    "MAS SAN MARTIN": "MAS SAN MARTIN",
    "MOVIMIENTO REGIONAL ANDE - MAR": "ANDE - MAR",
    "MOVIMIENTO ETNOCACERISTA REGIONAL DEL CUSCO": "MOVIMIENTO ETNOCACERISTA REGIONAL DEL CUSCO",
    "MOVIMIENTO POLITICO FRENTE AMPLIO REGIONAL PAISANOCUNA": "FRENTE AMPLIO REGIONAL PAISANOCUNA",
    "MOVIMIENTO REGIONAL PARA EL DESARROLLO CON SEGURIDAD Y HONRADEZ": "MOV. REGIONAL PARA EL DESARROLLO CON SEGURIDAD Y HONRADEZ",
    "PARTIDO PATRIOTICO DEL PERU": "PARTIDO PATRIOTICO DEL PERU",
    "MOVIMIENTO REGIONAL EL MAICITO": "EL MAICITO",
    "SALVEMOS AL PERU": "SALVEMOS AL PERU",
    "FRENTE PATRIOTA PERUANO": "FRENTE PATRIOTA PERUANO",
    "MOVIMIENTO INDEPENDIENTE UNIDOS POR JUNIN, SIERRA Y SELVA": "UNIDOS POR JUNIN, SIERRA Y SELVA",
    "LORETO RESTAURADO": "LORETO RESTAURADO",
    "MOVIMIENTO REGIONAL CONSTRUYENDO": "CONSTRUYENDO",
    "RENOVACION NACIONAL": "RENOVACION NACIONAL",
    "MOVIMIENTO NUEVA IZQUIERDA": "NUEVA IZQUIERDA",
    "AGRUPACION INDEPENDIENTE SI CUMPLE": "SI CUMPLE",
    "FRENTE DE MOVILIZACION SOCIAL": "FRENTE DE MOVILIZACION SOCIAL",
    "MOVIMIENTO PRODUCTIVO REGIONAL": "MOVIMIENTO PRODUCTIVO REGIONAL",
    "MOVIMIENTO INDEPENDIENTE REGIONAL HUANUCO PRIMERO": "HUANUCO PRIMERO",
    "MOVIMIENTO REGIONAL SIERRA Y SELVA CONTIGO JUNIN": "SIERRA Y SELVA CONTIGO JUNIN",
    "PARTIDO PAIS PARA TODOS": "PAIS PARA TODOS",
    "PARTIDO DEL BUEN GOBIERNO": "PARTIDO DEL BUEN GOBIERNO",
    "PARTIDO UNIDAD Y PAZ": "UNIDAD Y PAZ",
    "MOVIMIENTO INDEPENDIENTE FUERZA REGIONAL": "FUERZA REGIONAL",
    "COMUNIDAD POLITICA INKA PERU": "COMUNIDAD POLITICA INKA PERU",
    "PARTIDO DE LOS TRABAJADORES Y EMPRENDEDORES PTE - PERU": "PTE",
    "VERDAD Y HONRADEZ": "VERDAD Y HONRADEZ",
    "PARTIDO POLITICO FUERZA MODERNA": "FUERZA MODERNA",
    "UN CAMINO DIFERENTE": "UN CAMINO DIFERENTE",
    "PARTIDO POLITICO INTEGRIDAD DEMOCRATICA": "INTEGRIDAD DEMOCRATICA",
    "PARTIDO CIVICO OBRAS": "PARTIDO CIVICO OBRAS",
    "PARTIDO CIUDADANOS POR EL PERU": "CIUDADANOS POR EL PERU",
    "PARTIDO SICREO": "SI CREO",
    "PARTIDO POLITICO TODO CON EL PUEBLO": "TODO CON EL PUEBLO",
    "PARTIDO POLITICO PERUANOS UNIDOS : ¡SOMOS LIBRES!": "PERUANOS UNIDOS : ¡SOMOS LIBRES!",
    "PARTIDO DEMOCRATICO FEDERAL": "PARTIDO DEMOCRATICO FEDERAL",
    "ADELANTE PUEBLO UNIDO": "ADELANTE PUEBLO UNIDO",
    "UP UNIDAD POPULAR": "UP UNIDAD POPULAR",
    "PARTIDO POLITICO POPULAR VOCES DEL PUEBLO": "VOCES DEL PUEBLO",
    "PARTIDO POLITICO PUEBLO CONSCIENTE": "PUEBLO CONSCIENTE",
    "PARTIDO POLITICO COOPERACION POPULAR": "COOPERACION POPULAR",
    "BATALLA PERU": "BATALLA PERU",
    "ALIANZA ELECTORAL UNIDAD NACIONAL": "ALIANZA ELECTORAL UNIDAD NACIONAL",
    "RESTAURACION NACIONAL": "RESTAURACION NACIONAL",
    "PARTIDO HUMANISTA PERUANO": "PARTIDO HUMANISTA PERUANO",
    "PODEMOS POR EL PROGRESO DEL PERU": "PODEMOS POR EL PROGRESO DEL PERU",
    "PERU LIBERTARIO": "PERU LIBERTARIO",
    "MOVIMIENTO INDEPENDIENTE SOMOS PERU": "MOVIMIENTO INDEPENDIENTE SOMOS PERU",
    "SIEMPRE UNIDOS": "SIEMPRE UNIDOS",
    "PERUANOS POR EL KAMBIO": "PERUANOS POR EL KAMBIO",
    "FUERZA 2011": "FUERZA 2011",
    "IZQUIERDA UNIDA": "IZQUIERDA UNIDA",
    "ALIANZA PARA EL PROGRESO DEL PERU": "APP",
    "AGRUPACION INDEPENDIENTE UNION POR EL PERU - FRENTE AMPLIO": "UNION POR EL PERU - FRENTE AMPLIO",
    "MOVIMIENTO INDEPENDIENTE VAMOS VECINO": "VAMOS VECINO",
    "GANA PERU": "GANA PERU",
    "PARTIDO POPULAR CRISTIANO": "PPC",
    "CAMBIO 90 - NUEVA MAYORIA": "CAMBIO 90 - NUEVA MAYORIA",
    "UNIDAD NACIONAL": "UNIDAD NACIONAL",
    "MOVIMIENTO REGIONAL GANA AYACUCHO": "GANA AYACUCHO",
    "ALIANZA POR EL FUTURO": "ALIANZA POR EL FUTURO",
    "FREDEMO": "FREDEMO",
    "FRENTE DE CENTRO": "FRENTE DE CENTRO",
    "PARTIDO POPULAR CRISTIANO - PPC - UNIDAD NACIONAL": "PPC - UNIDAD NACIONAL",
    "PODER DEMOCRATICO REGIONAL": "PODER DEMOCRATICO REGIONAL",
    "AGRUPACION INDEPENDIENTE UNION POR EL PERU - SOCIAL DEMOCRACIA": "UNION POR EL PERU - SOCIAL DEMOCRACIA",
    "ALIANZA ELECTORAL PERU 2000": "PERU 2000",
    "DESPERTAR NACIONAL": "DESPERTAR NACIONAL",
    "MORAL Y DESARROLLO": "MORAL Y DESARROLLO",
    "MOVIMIENTO INDEPENDIENTE SOMOS PERU - CAUSA DEMOCRATICA": "SOMOS PERU - CAUSA DEMOCRATICA",
    "MOVIMIENTO POLITICO HECHOS Y NO PALABRAS": "HECHOS Y NO PALABRAS",
    "PARTIDO POLITICO NACIONAL PRIMERO PERU": "PRIMERO PERU",
    "SOMOS LIMA": "SOMOS LIMA",
    "TODOS POR LA VICTORIA": "TODOS POR LA VICTORIA",
    "ALIANZA ELECTORAL IZQUIERDA UNIDA": "ALIANZA ELECTORAL IZQUIERDA UNIDA",
    "AREQUIPA AVANCEMOS": "AREQUIPA AVANCEMOS",
    "CODE - PAIS POSIBLE": "CODE - PAIS POSIBLE",
    "FRENATRACA": "FRENATRACA",
    "JUNTOS POR JUNIN": "JUNTOS POR JUNIN",
    "MOVIMIENTO INDEPENDIENTE OBRAS SIEMPRE OBRAS": "OBRAS SIEMPRE OBRAS",
    "ORGANIZACION POLITICA LOCAL PROVINCIAL DIALOGO VECINAL": "DIALOGO VECINAL",
    "AGRUPACION INDEPENDIENTE AVANCEMOS": "AVANCEMOS",
    "ALIANZA ELECTORAL CAMBIO 90 - NUEVA MAYORIA": "CAMBIO 90 - NUEVA MAYORIA",
    "ALIANZA ELECTORAL JUNTOS POR LA LIBERTAD": "JUNTOS POR LA LIBERTAD",
    "ALIANZA ELECTORAL SOLUCION POPULAR": "SOLUCION POPULAR",
    "DECIDE": "DECIDE",
    "MOVIMIENTO AMPLIO PAIS UNIDO - MAPU": "MOVIMIENTO AMPLIO PAIS UNIDO",
    "MOVIMIENTO DE DESARROLLO LOCAL": "MOVIMIENTO DE DESARROLLO LOCAL",
    "MOVIMIENTO INDEPENDIENTE REGIONAL PURO ANCASH": "PURO ANCASH",
    "PROYECTO DE LA INTEGRACION PARA LA COOPERACION": "PROYECTO DE LA INTEGRACION PARA LA COOPERACION",
    "TODOS POR LAMBAYEQUE - MANOS LIMPIAS": "TODOS POR LAMBAYEQUE - MANOS LIMPIAS",
    "UNION DE IZQUIERDA REVOLUCIONARIA": "UNION DE IZQUIERDA REVOLUCIONARIA",
    "ACUERDO SOCIALISTA DE IZQUIERDA": "ACUERDO SOCIALISTA DE IZQUIERDA",
    "AGRUPACION INDEPENDIENTE UNION POR EL PERU": "UNION POR EL PERU",
    "ALIANZA IZQUIERDA UNIDA": "ALIANZA IZQUIERDA UNIDA",
    "CAMBIO 90": "CAMBIO 90"
};

// Función mágica que convierte el nombre largo en corto si existe
const getNombreCorto = (nombreLargo) => {
    if (!nombreLargo) return "Desconocido";

    const busquedaLimpia = nombreLargo.trim().toUpperCase().mon



    const key = nombreLargo.trim().toUpperCase();
    return DICCIONARIO_NOMBRES_CORTOS[key] || nombreLargo; // Si no lo encuentra, deja el largo intacto
};
// ===============================================



// ===============================================
// MOVIMIENTOS EXCLUIDOS DE LA MATEMÁTICA PERIODÍSTICA
// Partidos locales/regionales con INCLUIR = "NO"
// ===============================================
const PARTIDOS_EXCLUIDOS = ["TRABAJEMOS POR QUINCHES", "MOVIMIENTO INDEPENDIENTE COMPROMISO CAMPESINO", "MOVIMIENTO INDEPENDIENTE FRENTE POPULAR N° 3", "L.I. N° 5 FRENTE INDEPENDIENTE CRISTIANO LIBRE ACCION NAC.", "L.I. NRO 11 CAMBIO MUNICIPAL 95", "LUCHEMOS POR CAJAMARCA", "POR UN SAN JUAN SEGURO", "TODOS POR JUNIN", "PIURA EMPRENDEDOR", "FUERZA Y DESARROLLO", "TODOS POR MADRE DE DIOS", "L.I. NRO 7 GESTION POPULAR", "L.I. NRO 3 MOVIMIENTO INDEPENDIENTE DESARROLLO TECNOLOGIA Y MODERNIDAD", "TODOS CON TACNA", "UNIDOS POR EL CAMBIO DE PACHANGARA", "JUNTOS SI SE PUEDE", "¡ARRIBA PAIJAN!", "ORGANIZACION INDEPENDIENTE TODOS POR ILO", "MOVIMIENTO AL SOCIALISMO Y LIBERTAD", "FRENTE AMPLIO PARA EL DESARROLLO DE PUNO - FADEP", "FRENTE AMPLIO REGIONAL", "MOVIMIENTO INDEPENDIENTE HECHOS Y NO PALABRAS", "FRENTE DE AGRICULTORES LA UNION", "MOVIMIENTO INDEPENDIENTE \"LA PERLA\"", "ALTERNATIVA", "MOVIMIENTO REGIONAL \"PARA EL DESARROLLO E INTEGRACION DE AYACUCHO - DIA\"", "ORGANIZACION POLITICA MOPAV", "SOMOS LIBRES", "L.I. NRO 11 FRENTE INDEPENDIENTE SOLIDARIDAD UCHICINA", "MOVIMIENTO INDEPENDIENTE DE ACCION RENOVADORA DE SULLANA - MARS", "L.I. NRO 11 CAMBIO Y SOLUCION", "MOVIMIENTO DEMOCRATICO DE IZQUIERDA", "MOVIMIENTO INDEPENDIENTE FUERZA CAMPESINA", "COMPROMISO UCAYALINO", "L.I. N° 3 FRENTE DEMOCRATICO POPULAR", "MOVIMIENTO DE AFIRMACION SOCIAL - ACCION", "LA MOLINA 2000", "FRENTE UNIDO", "MOVIMIENTO INDEPENDIENTE \"RECUPEREMOS LINCE YA\"", "INTEGRACION DISTRITAL", "SALVEMOS LURIN", "LINDO HUARMEY", "MOVIMIENTO INDEPENDIENTE INNOVACION - SULLANA", "L.I. UNIDAD Y DESARROLLO PASQUEÑOS", "MOVIMIENTO INDEPENDIENTE REGIONAL HORA CERO", "MOVIMIENTO INDEPENDIENTE TRABAJANDO PARA TODOS", "UCAYALI DIGNIDAD", "MOVIMIENTO SOCIAL TUMBES UNIDO", "L.I. NRO 7 UNION POR EL PROGRESO", "INTEGRACION CHINCHANA", "MOVIMIENTO CIVICO AREQUIPA", "TRABAJO MAS TRABAJO", "L.I. NRO 13 MOV IND POR EL DESARROLLO DE MOQ", "L.I. NRO 11 MOVIMIENTO POLITICO INDEPENDIENTE MI PUEBLO", "ALTERNATIVA CAMPESINA", "PUCACACA AL 2000", "ENERGIA COMUNAL AMAZONICA", "VOLUNTAD INDEPENDIENTE DE DESARROLLO AMAZONICO", "MOVIMIENTO INDEPENDIENTE \"YAUYOS ERES TU\"", "L.I. NRO 11 SOMOS CAMBIO 95", "L.I. NRO 9 UNION POR EL PUEBLO", "U.T. VIVA LA MOLINA", "OPORTUNIDAD PARA TODOS", "L.I. NRO 7", "MIRAFLORES UNIDO", "MOVIMIENTO OBRAS", "AREQUIPA PRIMERO", "NUEVA IMAGEN", "MOVIMIENTO INDEPENDIENTE \"FUERZA ICA\"", "L.I. NRO 9 FRENATRACA", "L.I. NRO 11 FRENTE DE CONSTRUCCION Y DESARROLLO", "CUSCO LINDO", "ALIANZA POR AREQUIPA", "MOVIMIENTO REGIONAL INDEPENDIENTE DE CAMPESINOS OBREROS, EMPLEADOS Y ESTUDIANTES", "MOVIMIENTO INDEPENDIENTE \"NUEVO YUNGUYO\"", "L.I. NRO 41 MOVIMIENTOS JUNTOS POR BARRANCA", "IGUALDAD NACIONAL CRISTIANA AUTONOMA", "ALIANZA POPULAR INDEPENDIENTE", "MOVIMIENTO DE INTEGRACION PARA EL DESARROLLO", "VAMOS POR NASCA", "L.I. N° 19", "FRENTE AMPLIO PODER VECINAL", "L.I. NRO 15 ACCION VECINAL PRO PUNO", "L.I. N° 7 DESARROLLO Y RENOVACION - LIDER", "LUCHO POR CASTILLA", "CONTIGO LAREDO", "TRABAJO + TRABAJO", "MOVIMIENTO PARTICIPEMOS", "MOVIMIENTO POLITICO FUERZA HUANCAVELICA", "FRENTE METROPOLITANO", "CORAZON CHORRILLANO", "MOVIMIENTO INDEPENDIENTE \"FRENTE DE DESARROLLO CORRALES\"", "MOVIMIENTO INDEPENDIENTE TAMBOGRANDINO", "UNIDAD DEL PUEBLO", "ALIANZA ELECTORAL UNIDAD POPULAR", "TODOS POR BELEN", "MOVIMIENTO INDEPENDIENTE REGIONAL APURIMAC UNIDO", "MI DISTRITO", "L.I. NRO 9 SOMOS TAHUAMANU", "DEMOCRACIA CON VALORES", "ROCA FUERTE - SEGUNDA JERUSALEN", "FRENTE UNIFICADO LAMBAYECANO", "MOLLEBAYA AHORA", "LISTA INDEPENDIENTE FRENTE CIVICO", "MOVIMIENTO INDEPENDIENTE UNIDOS CONSTRUYENDO", "L.I. NRO 17 HONESTIDA Y TRABAJO", "MOVIMIENTO REGIONAL INDEPENDIENTE CON EL PERU", "MOVIMIENTO INDEPENDIENTE REGIONAL VAMOS LORETO", "UNION CARRIONINA", "MOVIMIENTO INDEPENDIENTE \"PROGRESO VERDE\"", "MOVIMIENTO INDEPENDIENTE FUERZA CONSTRUCTORA", "POR UN FUTURO MEJOR", "L.I. CAMBIO 93", "DIALOGO VECINAL", "MOVIMIENTO DE IZQUIERDA PAMPINA", "MOVIMIENTO INDEPENDIENTE \"FRENTE SOCIAL NUEVA PROPUESTA\"", "MOVIMIENTO AGRARIO POPULAR UCAYALINO", "RUNA", "UNIDAD CAMPESINA INDEPENDIENTE", "L.I N° 3 UDECA", "TARMA CORAZON", "ACCION POR EL BIENESTAR", "MOVIMIENTO CAMBIO 93", "MOVIMIENTO INDEPENDIENTE IDEAS", "MOVIMIENTO POLITICO REGIONAL ENERGIA COMUNAL AMAZONICA", "LA PERLA EMPRENDE, SI SE PUEDE", "MOVIMIENTO INDEPENDIENTE JUNTOS POR EL DESARROLLO", "PIURA RENACE", "L.I.N° 3", "MOVIMIENTO INDEPENDIENTE \"FRENTE DESARROLLO LUCANAS - FREDEL\"", "SECHURANOS UNIDOS", "MOVIMIENTO INDEPENDIENTE UNION YUNGAINA", "VICTORIA AMAZONENSE", "FUERZA REGIONAL AMAZONICA DE MADRE DE DIOS", "OBRAS Y MAS OBRAS", "PLATAFORMA DEMOCRATICA", "LISTA 5", "TODOS UNIDOS POR NUESTRO AYACUCHO", "MOVIMIENTO INDEPENDIENTE \"INTEGRACION REGIONAL\"", "L.I. NRO 21 BARRANCA AL CAMBIO", "SOMOS MIRAFLORES 2002", "MOVIMIENTO REGIONAL JUSTICIA Y CAPACIDAD", "FUERZA CHANCHAMAYO", "INDEPENDIENTE ACUERDO POPULAR", "JUNTOS GOBERNAREMOS", "SIGAMOS MODERNIZANDO PIMENTEL", "ALTERNATIVA LIBRE", "UNION REGIONAL TRANSPARENTE", "MOVIMIENTO INDEPENDIENTE \"AMANECER AGRARIO - MIAA\"", "MOVIMIENTO INDEPENDIENTE AMISTAD", "COMITE INDEPENDIENTE VECINAL DE PUNTA HERMOSA", "MOVIMIENTO INDEPENDIENTE ALTERNATIVA ANDINA", "MOVIMIENTO INDEPENDIENTE \"FUERZA COMUNAL\"", "MOVIMIENTO HUANUCO UNIDO", "ALIANZA REGIONAL INDEPENDIENTE", "POR EL AVANCE DEL SUR", "SI TRABAJA", "UNIDAD Y DESARROLLO", "CHINCHA SI PUEDE", "L.I N° 5 FRENTE INDEPENDIENTE DE RENOVACION Y CAM", "PARTIDO DE INTEGRACION NACIONAL", "MOVIMIENTO INDEPENDIENTE \"UNIDOS POR TINGO MARIA\"", "FRENTE POPULAR DE IZQUIERDA NUEVO COMAS", "MOVIMIENTO INDEPENDIENTE \"RESURGIR SALPINO\"", "L.I. NRO 7 JUNTOS POR SAN LUIS", "PADIN - MOVIMIENTO INDEPENDIENTE REGIONAL", "MOVIMIENTO REGIONAL FUERZA POR MADRE DE DIOS", "MOVIMIENTO INDEPENDIENTE CENTENARIO ESPINAR", "L.I. NRO 17 INKA PACHAKUTEQ", "VIVA LA MOLINA", "ALIANZA POR TACNA", "ADELANTE CHICLAYO", "CONTIGO MOQUEGUA", "SALVEMOS HUARAZ", "TAYACAJA 98", "CAPACIDAD CIUDADANA AL DESARROLLO", "DESARROLLO SOCIAL AMAZONENSE", "L.I. N° 13 CERRO BAUL", "L.I N° 3 MOVIMIENTO INDEPENDIENTE REQUENA", "TE QUIERO WANCHAQ", "MOVIMIENTO POLITICO INDEPENDIENTE \"CHIM PUM CALLAO\"", "IZQUIERDA PAMPINA", "NUEVO SATIPO", "MOVIMIENTO INDEPENDIENTE REIVINDICADOR DE PADRE ABAD (MIRPA)", "TACNA HEROICA", "CONTIGO SIVIA", "FRENTE UNITARIO POPULAR", "L.I. NRO 33 MAYORIA CON EL CAMBIO EN LA CONVENCION", "FRENTE UNITARIO VECINAL PROGRESISTA ALTO PIURA", "MOVIMIENTO DE IDENTIDAD Y CONFIANZA", "ORGANIZACION POLITICA INDEPENDIENTE DISTRITAL ALTERNATIVA VERDE", "NUEVA VICTORIA", "L.I. NRO 15 REGIONAL FUERZA UCAYALINA", "L.I. NRO 7 VAMOS CHURCAMPA", "ACCION CIVICA", "FUERZA CAMPESINA", "ACCION SOLIDARIA", "L.I. MOVIMIENTO REPRESENTACION DISTRITAL SANTA ANITA", "JUNTOS ALCANZAREMOS EL NORTE \"MI JAEN\"", "MOVIMIENTO ETNOCACERISTA REGIONAL AMA SUA, AMA LLULLA, AMA QUELLA", "ORGANIZACION INDEPENDIENTE ASHANINKA DEL PICHIS", "L.I.N° 3 OBRAS", "PISCO AL FUTURO", "MOVIMIENTO POLITICO INDEPENDIENTE \"TODOS TAWANTINSUYO\"", "SALVEMOS LOS OLIVOS", "UNIDOS POR RECUAY", "FRATERNIDAD FAJARDINA", "L.I. NRO 7 ORGANIZACION PARA EL DESARROLLO DE PATAZ", "MOVIMIENTO INDEPENDIENTE DE DESARROLLO LOCAL - MODELO", "MOVIMIENTO INDEPENDIENTE FUERZA CAMPESINA REGIONAL", "L.I. NRO 13 SOMOS HUERTAS - 95", "MOVIMIENTO INDEPENDIENTE COMAS CON FE", "PODER PARA TODOS", "POR EL DESARROLLO DE CONTRALMIRANTE VILLAR", "CAJAMARCA EN ACCION", "INNOVACION", "MOVIMIENTO UNIDOS POR PUEBLO LIBRE", "TODOS SOMOS CHACLACAYO", "MOVIMIENTO INDEPENDIENTE REIVINDIQUEMOS LORETO", "VAMOS CAYMA CON LA NUEVA GENERACION 2014", "MOVIMIENTO INDEPENDIENTE \"ALTERNATIVA POR LA DEMOCRACIA Y DESARROLLO REGIONAL ALPODER\"", "LA ESPERANZA DE LA PROVINCIA DE CHEPEN", "L.I. NRO 9 MID PASCO", "HUANCAVELICA SOSTENIBLE", "MOVIMIENTO POPULAR VASO DE LECHE", "FRENTE INDEPENDIENTE DE BIGOTE", "MOVIMIENTO INDEPENDIENTE NUESTRO ILO-MOQUEGUA", "MAS ACCION", "L.I. N° 7 FRENTE INDEPENDIENTE AGRICOLA", "PRODE - PROGRESO Y DESARROLLO", "MOVIMIENTO INDEPENDIENTE TODOS POR LAMBAYEQUE", "LOS INDEPENDIENTES", "MOVIMIENTO ECOLOGICO ALTERNATIVA VERDE - LOS VERDES", "FUTURO PARA TODOS", "EL GRAN CAMINO", "MOVIMIENTO MACROREGIONAL TODAS LAS SANGRES - APURIMAC", "L.I. N° 3 FRENTE INDEPENDIENTE RENOVADOR (FIR)", "LUCHO POR EL RIMAC", "FUERZA COMUNAL", "RECUPEREMOS VICTOR LARCO", "L.I. NRO 21 CAMBIO", "MOVIMIENTO REGIONAL AREQUIPA UNIDA", "L.I. NRO 11 TRABAJO + TRABAJO", "UNIDOS POR CHINCHA", "MOVIMIENTO LIBERTAD", "VAMOS SULLANA", "CONCIENCIA CHALACA", "MOVIMIENTO INDEPENDIENTE AMANECER ACOLLINO", "ARMANDO EL PROGRESO", "FRENTE RENACIMIENTO SURQUILLANO", "RESURGIR SALPINO", "MOVIMIENTO INDEPENDIENTE \"ACCION Y DESARROLLO\"", "L.I. NRO 7 ORDEN Y DESARROLLO", "ARRIBA CALANA", "COORDINADORA NACIONAL DE INDEPENDIENTES", "L.I. NRO 5", "MOVIMIENTO INDEPENDIENTE \"LUCHEMOS POR HUANUCO\"", "UNIDOS POR EL DESARROLLO", "CONTIGO BREÑA", "UNION POPULAR CHINCHANA", "POR MIRAFLORES JUNTOS PODEMOS...", "FRENTE INDEPENDIENTE UNIDAD VECINAL DE LURIN", "VALE ANCASH", "L.I. NRO 3 UNIDOS POR LA RENOVACION", "FRENTE ESPERANZA POR TACNA", "PROYECTO VECINAL", "MOVIMIENTO REGIONAL LAMBAYECANO PODER PARA TODOS", "L.I. NRO 09 OBRAS + OBRAS", "TUMBES RENACE", "ALIANZA POPULAR INDEPENDIENTE \"VICTOR LARCO HERRERA\"", "RECONSTRUCCION Y DESARROLLO", "ADELANTE A TRIUNFAR", "PAUCARPATA DESARROLLO TOTAL", "MOVIMIENTO POLITICO INDEPENDIENTE \"DEMOCRACIA ANDINA REGIONAL\"", "FRENTE DE INTEGRACION VECINAL DE UTCUBAMBA", "FRENTE AMPLIO", "MUVA", "L.I. NRO 25 SOMOS MM", "L.I. NRO 3 UNIDOS POR CHEPEN", "MOVIMIENTO ACCION SOCIAL INDEPENDIENTE", "MOVIMIENTO INDEPENDIENTE SOMOS NUEVA GENERACION", "PUJANZA SAMEGUANA", "L.I. NRO 19 UNIDAD VECINAL CASTELLANA", "NUESTRO ILO - MOQUEGUA", "CONTIGO REGION", "FRENTE DE DESARROLLO JUNTOS POR PAUCARPATA", "FRENTE INDEPENDIENTE PASCO UNIDO", "L.I. NRO 9 IZQUIERDA UNIDA", "ORGANIZACION POLITICA REGIONAL \"VICTORIA CHALACA\"", "L.I. NRO 3 MOVIMIENTO INDIGENA 95", "MOVIMIENTO INDEPENDIENTE \"POR LA AGRICULTURA Y TRABAJO DE CHAO\"", "L.I. NRO 21 MOV IND L AMERICAS", "DIGNIDAD Y ESPERANZA FERREÑAFANA", "RENOVACION CONVENCIANA", "L.I. NRO 9 NUEVA ALTERNATIVA", "DESARROLLO PARA TACNA", "L.I. N° 7", "L.I. NRO 9 SUCRE TECNOLOGIA Y DESARROLLO", "POR LAS COMUNIDADES FUENTE DE INTEGRACION ANDINA DE PUNO - CONFIA - PUNO", "LIDER", "ALIANZA HORA CERO FUERZA POPULAR", "PODER Y CAMBIO AL 2010", "AGROPECUARIO HONORIA PROGRESO", "LINEA DE IDENTIDAD Y DESARROLLO SATIPEÑO - LIDER´S", "MOVIMIENTO CIVICO NACIONAL 7 DE JUNIO INDEPENDIENTES PASQUEÑOS", "ANCASH DIGNIDAD", "MOVIMIENTO INDEPENDIENTE TALARA SOMOS GENTE JOVEN", "MOVIMIENTO INDEPENDIENTE OBRAS AL 2000", "MOVIMIENTO CAMPESINO ATUSPARIA", "UNIDAD REGIONAL", "MOVIMIENTO INDEPENDIENTE UVAS - UNION VECINAL DE AVANZADA SUNAMPINA", "TODO POR UCAYALI", "L.I. NRO 5 FRENTE INDEPENDIENTE RENOVADOR - FIR", "MOV. DEMOCRATICO DE IZQUIERDA", "MOVIMIENTO POPULAR REGIONAL", "L.I. NRO 25 FRATERNIDAD NACIONAL", "PUMA 2011", "MOVIMIENTO UCHICINO DE DESARROLLO INTEGRAL MUDI", "MOVIMIENTO INDEPENDIENTE SALVEMOS AYACUCHO", "DIGNIDAD VECINAL", "L.I. NRO 5 UNION POR CARHUAZ", "ACCION Y DESARROLLO", "UPA-TCU UNIDOS PUEBLO AGRO TAMBOGRANDE CASERIOS UNIDOS", "SALVEMOS MIRAFLORES", "PARTIDO SOCIALISTA REVOLUCIONARIO", "LISTA INDEPENDIENTE \"UNION PARA EL DESARROLLO DEL ALTO PIURA\" - UDAP", "MOVIMIENTO DE INTEGRACION INDIGENA Y CAMPESINO", "FRENTE TACNEÑISTA", "L.I. NRO 7 MOV IND FRENTE POPULAR POR MADRE DE DIOS", "L.I. NRO 51 MOVIMIENTO ACCION CIVICA INDEPENDIENTE", "SELVA SUR", "NACE UNA ESPERANZA", "FUERZA POR MADRE DE DIOS", "LISTA 3", "MOVIMIENTO INDEPENDIENTE REGIONAL \"FRENTE UNIDO PROGRESISTA\"", "ESPERANZA CIUDADANA", "MOVIMIENTO ETNOCACERISTA AREQUIPA", "MOVIMIENTO INDEPENDIENTE \"NUEVO FUTURO DE ILO\"", "L. I. PAZ Y DESARROLLO", "RECONSTRUCCION EFECTIVA", "MOVIMIENTO CIVICO REGIONAL \"TODO POR UCAYALI\"", "MOVIMIENTO INDEPENDIENTE CONTIGO CHORRILLOS", "MOVIMIENTO INKA PACHACUTEQ", "UNIDOS PUEBLO AGRO TAMBOGRANDE CASERIOS UNIDOS", "FRENTE INDEPENDIENTE EL PUEBLO ORGANIZADO", "MOVIMIENTO INDEPENDIENTE INTEGRACIONISTA ALTO AMAZONAS M.I.I.A.A.", "L.I. NRO 11 95 YUNGUYO AL FUTURO", "CASTILLA AVANZA", "MOVIMIENTO INDEPENDIENTE \"JUNTOS POR EL CALLAO\"", "UNIDOS POR EL CAMBIO ZARUMILLA", "SOMOS MARIANO MELGAR", "ACCION DE GOBERNABILIDAD PARA LA UNIDAD ANDINA", "L.I. NRO 13 DE LA UNIV", "BARRANCO SOLIDARIO", "MOVIMIENTO INDEPENDIENTE PROVINCIAL \"CONCERTANDO SI PODEMOS\"", "LISTA INDEPENDIENTE \"CONFRATERNIDAD TAYACAJINA\"", "CHIMPUM - CALLAO", "MOVIMIENTO INDEPENDIENTE AMOR POR MADRE DE DIOS", "CIENCIA Y ACCION MOVILIZADORA DE UCAYALI", "L.I N° 13 FRENTE PROGRESISTA DE MASAS", "L.I. NRO 17", "ARRIBA CAÑETE", "L.I. N° 5 UNIDAD POPULAR"];

// ===============================================
// FUNCIÓN MAESTRA DE CONTEO DE CAMISETAS
// ===============================================
function calcularCamisetasUnicas(candidato) {
    let historialSeguro = ensureArray(candidato.historialElectoral);
    
    // Extraemos partidos y quitamos vacíos
    let partidosCrudos = historialSeguro.map(h => h.partido).filter(Boolean);
    if (candidato.partidoActual) partidosCrudos.push(candidato.partidoActual);
    
    const limpiarNombre = (nombre) => nombre.trim().toUpperCase().replace(/\.$/, '');

    // === EL FILTRO FALTANTE QUE APLICA LA REGLA EDITORIAL ===
    partidosCrudos = partidosCrudos.filter(p => !PARTIDOS_EXCLUIDOS.includes(limpiarNombre(p)));
    // =========================================================

    // Buscador de Raíz Canónica (Resuelve cadenas A->B->C y unifica JNE vs CSV)
    const obtenerRaizCanonica = (partido) => {
        let conectados = new Set([partido]);
        let queue = [partido];
        
        while(queue.length > 0) {
            let actual = queue.shift();
            
            // Buscar hacia adelante
            let destino = DICCIONARIO_CLONES[actual];
            if (destino && !conectados.has(destino)) {
                conectados.add(destino);
                queue.push(destino);
            }
            
            // Buscar hacia atrás
            for (let origen in DICCIONARIO_CLONES) {
                if (DICCIONARIO_CLONES[origen] === actual && !conectados.has(origen)) {
                    conectados.add(origen);
                    queue.push(origen);
                }
            }
        }
        return Array.from(conectados).sort()[0];
    };

    // Homologamos el diccionario de alianzas a raíces universales
    const ALIANZAS_RAIZ = {};
    for (let alianza in DICCIONARIO_ALIANZAS) {
        let alianzaRaiz = obtenerRaizCanonica(limpiarNombre(alianza));
        let miembrosRaiz = DICCIONARIO_ALIANZAS[alianza].map(limpiarNombre).map(obtenerRaizCanonica);
        ALIANZAS_RAIZ[alianzaRaiz] = miembrosRaiz;
    }

    // FASE 1: Limpieza de Clones y Nomenclatura
    let partidosClonados = partidosCrudos.map(limpiarNombre).map(obtenerRaizCanonica);
    let pSet = Array.from(new Set(partidosClonados));

    // FASE 2: Absorción de Alianzas
    let partidosFinales = [];

    for (let p of pSet) {
        if (ALIANZAS_RAIZ[p]) {
            let miembrosAlianza = ALIANZAS_RAIZ[p];
            let tieneMiembro = false;
            
            for (let miembro of miembrosAlianza) {
                if (pSet.includes(miembro) && p !== miembro) {
                    tieneMiembro = true;
                    break;
                }
            }

            if (tieneMiembro) {
                continue; // REGLA 2: Se absorbe (No suma)
            } else {
                partidosFinales.push(p); // REGLA 3: Alianza invitada (Suma)
            }
        } else {
            partidosFinales.push(p); // REGLA NORMAL (Suma)
        }
    }

    return partidosFinales.length;
}



// ===============================================
// INICIALIZACIÓN
// ===============================================
document.addEventListener("DOMContentLoaded", initApp);

async function initApp() {
    try {
        const [resCand, resPart] = await Promise.all([
            fetch(CONFIG.archivos.masterJSON),
            fetch(CONFIG.archivos.partidosJSON).catch(() => ({ ok: false })) 
        ]);

        const datosCrudos = await resCand.json();
        
        // FILTRO VISUAL
        todosLosCandidatos = datosCrudos.filter(c => !CONFIG.filtros.partidosOcultosVisualmente.includes(c.partidoActual));
        
        if (resPart.ok) diccionarioPartidos = await resPart.json();

        const partidosSet = new Set();
        todosLosCandidatos.forEach(c => { if(c.partidoActual) partidosSet.add(c.partidoActual); });
        const partidosUnicos = Array.from(partidosSet).sort();

        const cargosSet = new Set();
        todosLosCandidatos.forEach(c => {
            if(Array.isArray(c.cargos)) c.cargos.forEach(cg => cargosSet.add(cg));
            else if(c.cargo) cargosSet.add(c.cargo);
        });
        const cargosUnicos = Array.from(cargosSet).sort();

        // 1. Ranking 
        const selectRankings = document.getElementById('ranking-partido-select');
        if(selectRankings) {
            populateSelects('ranking-partido-select', partidosUnicos, 'partido');
            selectRankings.addEventListener('change', (e) => renderRankings(calcularRankings(todosLosCandidatos, e.target.value), e.target.value));
        }
        renderRankings(calcularRankings(todosLosCandidatos, "ALL"), "ALL");

        // 2. Comparador
        populateSelects('select-partido-1', partidosUnicos, 'partido');
        populateSelects('select-partido-2', partidosUnicos, 'partido');
        populateSelects('select-cargo-1', cargosUnicos, 'cargo'); 
        populateSelects('select-cargo-2', cargosUnicos, 'cargo');
        
        setupBuscadorComparador('input-busqueda-1', 'select-partido-1', 'preselector-panel-1', 'results-container-1');
        setupBuscadorComparador('input-busqueda-2', 'select-partido-2', 'preselector-panel-2', 'results-container-2');
        renderTarjetaCandidato(null, 'results-container-1');
        renderTarjetaCandidato(null, 'results-container-2');

        // 3. Heatmap
        const selectHeatmap = document.getElementById('heatmap-partido-select');
        if(selectHeatmap) {
            populateSelects('heatmap-partido-select', partidosUnicos, 'partido');
            selectHeatmap.addEventListener('change', (e) => renderHeatmap(todosLosCandidatos, e.target.value));
        }
        renderHeatmap(todosLosCandidatos, "ALL");

        // 4. Timeline
        const selectTimeline = document.getElementById('timeline-partido-select');
        if(selectTimeline) {
            populateSelects('timeline-partido-select', partidosUnicos, 'partido');
            selectTimeline.addEventListener('change', (e) => renderTimeline(todosLosCandidatos, e.target.value));
        }
        renderTimeline(todosLosCandidatos, "ALL");

        // ==========================================
        // 5. Ranking de Perdedores
        // ==========================================
        renderRankingPerdedores(todosLosCandidatos);

    } catch (error) {
        console.error("Fallo al cargar datos:", error);
    }
}

// ===============================================
// CONSTRUCTOR DE SELECTORES
// ===============================================
function populateSelects(id, options, tipo = "partido") {
    const nativeSelect = document.getElementById(id);
    if(!nativeSelect) return;

    nativeSelect.innerHTML = `<option value="ALL">Todos los ${tipo === 'cargo' ? 'cargos' : 'partidos'}</option>`;
    options.forEach(opt => nativeSelect.innerHTML += `<option value="${opt}">${opt}</option>`);
    nativeSelect.style.display = 'none';

    if(nativeSelect.nextElementSibling && nativeSelect.nextElementSibling.classList.contains('custom-select-wrapper')) {
        nativeSelect.nextElementSibling.remove();
    }

    const wrapper = document.createElement('div');
    wrapper.className = 'custom-select-wrapper';
    
    const isComparador = id.includes('select-partido-1') || id.includes('select-partido-2') || id.includes('select-cargo');
    wrapper.style.width = isComparador ? '100%' : '450px'; 
    wrapper.style.minWidth = isComparador ? 'auto' : '450px';

    const renderContent = (valor, etiqueta) => {
        if (tipo === 'cargo') return `<span>${etiqueta}</span>`;
        if (valor === 'ALL') return `<span style="font-weight: bold;">${etiqueta}</span>`;
        
        const idPart = normalizarId(valor);
        const infoPart = diccionarioPartidos[idPart];
        const logoUrl = (infoPart && infoPart.logo) ? getUrlImagen(infoPart.logo) : '';
        
        const imgHtml = logoUrl ? `<img src="${logoUrl}" class="c-logo" onerror="this.outerHTML='<div class=\\'c-icon-placeholder\\'></div>'" />` : `<div class="c-icon-placeholder"></div>`;
        return `${imgHtml} <span>${etiqueta}</span>`;
    };

    const trigger = document.createElement('div');
    trigger.className = 'custom-select-trigger';
    trigger.innerHTML = `<span class="c-text">${renderContent('ALL', `Todos los ${tipo === 'cargo' ? 'cargos' : 'partidos'}`)}</span> <span class="c-arrow">▼</span>`;

    const optionsPanel = document.createElement('div');
    optionsPanel.className = 'custom-select-options';

    const createOption = (valor, etiqueta) => {
        const optDiv = document.createElement('div');
        optDiv.className = 'custom-option';
        optDiv.innerHTML = renderContent(valor, etiqueta);
        optDiv.addEventListener('click', () => {
            trigger.querySelector('.c-text').innerHTML = optDiv.innerHTML;
            nativeSelect.value = valor;
            nativeSelect.dispatchEvent(new Event('change')); 
            optionsPanel.classList.remove('open');
        });
        optionsPanel.appendChild(optDiv);
    };

    createOption('ALL', `Todos los ${tipo === 'cargo' ? 'cargos' : 'partidos'}`);
    options.forEach(opt => {
        // En lugar de pasar el opt largo, pasamos el corto a la interfaz
        let etiquetaCorta = (tipo === 'partido') ? getNombreCorto(opt) : opt;
        createOption(opt, etiquetaCorta);
    });
    trigger.addEventListener('click', (e) => {
        e.stopPropagation();
        document.querySelectorAll('.custom-select-options').forEach(p => { if(p !== optionsPanel) p.classList.remove('open'); });
        optionsPanel.classList.toggle('open');
    });

    wrapper.appendChild(trigger);
    wrapper.appendChild(optionsPanel);
    nativeSelect.parentNode.insertBefore(wrapper, nativeSelect.nextSibling);
}

document.addEventListener('click', (e) => {
    if(!e.target.closest('.custom-select-wrapper')) {
        document.querySelectorAll('.custom-select-options').forEach(p => p.classList.remove('open'));
    }
});

// ===============================================
// FASE 1: RANKINGS DINÁMICOS Y FILTRADOS
// ===============================================
function calcularRankings(candidatos, partidoFiltro = "ALL") {
    // 'pool' es la lista filtrada por el dropdown (afectará a la columna 1)
    let pool = candidatos;
    if (partidoFiltro !== "ALL") pool = candidatos.filter(c => c.partidoActual === partidoFiltro);

    // RANKING 1: Cambios de Camiseta usando la nueva lógica de clusters
    let rankingCamisetas = pool.map(c => {
        return { ...c, metrica: calcularCamisetasUnicas(c) };
    }).sort((a, b) => b.metrica - a.metrica).slice(0, 5);

    // RANKING 2: PARTIDOS CON MÁS CAMALEONES (SIEMPRE GLOBAL)
    const conteoPartidos = {};
    
    // Usamos la nueva lógica de clusters para saber si el candidato es camaleón
    candidatos.forEach(c => {
        let totalCamisetas = calcularCamisetasUnicas(c);
        if (totalCamisetas > 1) {
            conteoPartidos[c.partidoActual] = (conteoPartidos[c.partidoActual] || 0) + 1;
        }
    });

    let rankingPartidos = Object.entries(conteoPartidos)
        .map(([nombrePartido, cantidad]) => {
            const idPart = normalizarId(nombrePartido);
            const logoPartido = diccionarioPartidos[idPart] ? diccionarioPartidos[idPart].logo : null;
            return {
                nombre: nombrePartido,
                metrica: cantidad,
                partidoActual: null, // Evita la medallita doble
                idFoto: logoPartido  // Manda el logo al círculo principal
            };
        })
        .sort((a, b) => b.metrica - a.metrica)
        .slice(0, 5);

    return [
        { titulo: "Top 5 con más cambios de camiseta", data: rankingCamisetas, label: "camisetas" },
        { titulo: "Partidos con más camaleones", data: rankingPartidos, label: "candidatos" }
    ];
}



function renderRankings(rankingsData, partidoFiltro = "ALL") {
    const wrapper = document.getElementById('rankings-wrapper');
    if(!wrapper) return;

    let html = '';

    rankingsData.forEach(ranking => {
        if(ranking.data.length === 0) {
            html += `<div class="ranking-column" style="border-top: none !important;"><div class="ranking-header">${ranking.titulo}</div><p style="color:#888; font-size:13px; text-align:center; padding:20px;">Sin datos o nadie cumple el criterio</p></div>`;
            return;
        }

        // ========================================================
        // EL TRUCO: Detectamos qué columna estamos dibujando
        // Si la etiqueta es "candidatos", es el ranking de partidos
        // ========================================================
        const isPartidos = ranking.label === "candidatos"; 
        
        // Estilo dinámico: Gris para rostros, Color para logos de partidos
        const imgStyle = isPartidos 
            ? "width:100%; height:100%; object-fit:contain; border-radius:50%; background-color:#fff; padding: 2px;" // Partidos (A color)
            : "width:100%; height:100%; object-fit:cover; border-radius:50%; filter: grayscale(100%);"; // Rostros (Gris)

        const top1 = ranking.data[0];
        const resto = ranking.data.slice(1); 
        
        const fotoTop1 = top1.idFoto ? `<img src="${getUrlImagen(top1.idFoto)}" style="${imgStyle}" onerror="this.outerHTML='${getInitials(top1.nombre)}'"/>` : getInitials(top1.nombre);

        let badgeTop1 = '';
        if(top1.partidoActual) {
            const idPart = normalizarId(top1.partidoActual);
            if(diccionarioPartidos[idPart]?.logo) {
                badgeTop1 = `<img src="${getUrlImagen(diccionarioPartidos[idPart].logo)}" class="party-badge-mini" onerror="this.style.display='none'"/>`;
            }
        }

        let colHtml = `
            <div class="ranking-column" style="border-top: none !important;">
                <div class="ranking-header">${ranking.titulo}</div>
                <div class="chameleon-top">
                    <div class="photo" style="position: relative; background-color: #eee; display: flex; align-items: center; justify-content: center;">
                        ${fotoTop1}
                        ${badgeTop1}
                    </div>
                    <div class="chameleon-name">${top1.nombre}</div>
                    <div class="chameleon-metric"><span>${top1.metrica}</span> ${ranking.label}</div>
                </div>
                <div class="chameleon-list">
        `;

        resto.forEach((cand, index) => {
            const fotoResto = cand.idFoto ? `<img src="${getUrlImagen(cand.idFoto)}" style="${imgStyle}" onerror="this.outerHTML='${getInitials(cand.nombre)}'"/>` : getInitials(cand.nombre);
            
            let badgeResto = '';
            if(cand.partidoActual) {
                const idPart = normalizarId(cand.partidoActual);
                if(diccionarioPartidos[idPart]?.logo) {
                    badgeResto = `<img src="${getUrlImagen(diccionarioPartidos[idPart].logo)}" class="party-badge-mini" onerror="this.style.display='none'"/>`;
                }
            }

            colHtml += `
                <div class="chameleon-item">
                    <div class="pos">${index + 2}</div>
                    <div class="photo" style="position: relative; background-color: #eee; display: flex; align-items: center; justify-content: center; font-size: 14px; font-weight: bold; color: #555;">
                        ${fotoResto}
                        ${badgeResto}
                    </div>
                    <div class="info">
                        <div class="name">${cand.nombre}</div>
                        <div class="metric">${cand.metrica} ${ranking.label}</div>
                    </div>
                </div>
            `;
        });
        colHtml += `</div></div>`;
        html += colHtml;
    });
    wrapper.innerHTML = html;
}

// ===============================================
// FASE 2: COMPARADOR CARA A CARA
// ===============================================

function generarRopaHTML(historial, tipoRopa) {
    if (!historial || historial.length === 0) {
        return `<p style="text-align:left; font-size:14px; color:#888; padding: 10px 0; margin:0; font-style: italic;">Sin registros previos.</p>`;
    }
    
    return historial.map(h => {
        const idPart = normalizarId(h.partido);
        const infoPart = diccionarioPartidos[idPart];
        
        const imgRopaBase = `<img src="${CONFIG.rutas.baseFotos}${tipoRopa}" style="width: 100%; height: 100%; object-fit: contain; position: absolute; top: 0; left: 0; z-index: 1;" onerror="this.style.display='none'"/>`;

        let logoImg = '';
        if (infoPart && infoPart.logo) {
            const estiloLogo = tipoRopa === 'camiseta.png' 
                ? 'width: 16px; height: 16px; position: absolute; top: 25%; right: 25%; z-index: 2; object-fit: contain;' 
                : 'width: 14px; height: 14px; position: absolute; bottom: 20%; left: 30%; z-index: 2; object-fit: contain;';
            logoImg = `<img src="${getUrlImagen(infoPart.logo)}" style="${estiloLogo}" onerror="this.style.display='none'"/>`;
        }

        const anioLimpio = extraerAnioInicial(h.anio) || h.anio || 'N/A';
        // APLICAMOS LA MAGIA AQUÍ:
        const nombreLimpioParaUI = getNombreCorto(h.partido);

        return `
        <div class="jersey-item">
            <div class="jersey-placeholder" style="position: relative; background: transparent; border: none; box-shadow: none;">
                ${imgRopaBase}
                ${logoImg}
            </div>
            <div class="jersey-year">${anioLimpio}</div>
            <div class="jersey-party-name" title="${h.partido}">${nombreLimpioParaUI}</div>
            <div class="jersey-role">${h.rol || ''}</div>
        </div>
        `;
    }).join('');
}


// ===============================================
// RENDERIZADO DE LA TARJETA DEL CANDIDATO
// ===============================================

// ===============================================
// RENDERIZADO DE LA TARJETA DEL CANDIDATO
// ===============================================
function renderTarjetaCandidato(candidato, containerId) {
    const container = document.getElementById(containerId);
    if(!container) return;

    if (!candidato) {
        container.innerHTML = `<div style="background:#f9f9f9; border: 1px dashed #ccc; padding:40px 20px; text-align:center; border-radius:6px; color:#888;">Utiliza el buscador superior para seleccionar a un candidato y ver su historial aquí.</div>`;
        return;
    }

    let pActual = candidato.partidoActual || "INDEPENDIENTE";
    
    // --- MAGIA AQUÍ: Usamos el nombre corto para la interfaz ---
    let pActualCorto = getNombreCorto(pActual); 
    
    let colorPartido = CONFIG.colores.partidos[pActual] || CONFIG.colores.partidos["DEFECTO"];
    let iniciales = getInitials(candidato.nombre);
    
    let fotoPerfil = candidato.idFoto ? `<img src="${getUrlImagen(candidato.idFoto)}" style="width:100%; height:100%; object-fit:cover; border-radius:50%; filter: grayscale(100%);" onerror="this.outerHTML='<span style=\\'font-size: 24px; font-weight: bold;\\'>${iniciales}</span>'"/>` : `<span style="font-size: 24px; font-weight: bold;">${iniciales}</span>`;
    
    let cargosLabel = Array.isArray(candidato.cargos) ? candidato.cargos.join(' / ') : (candidato.cargos || '');

    const postulacion2026 = {
        anio: "2026",
        partido: pActual,
        rol: cargosLabel || "Candidato"
    };

    let historialElectoralSeguro = ensureArray(candidato.historialElectoral);

    // Filtro visual
    const limpiarNombre = (nombre) => nombre.trim().toUpperCase().replace(/\.$/, '');
    historialElectoralSeguro = historialElectoralSeguro.filter(h => !PARTIDOS_EXCLUIDOS.includes(limpiarNombre(h.partido)));

    let historialElectoralOrdenado = historialElectoralSeguro.slice().sort((a, b) => extraerAnioInicial(a.anio) - extraerAnioInicial(b.anio));
    historialElectoralOrdenado.push(postulacion2026); 

    let camElectorales = generarRopaHTML(historialElectoralOrdenado, 'camiseta.png');

    let totalCamisetas = calcularCamisetasUnicas(candidato);

    const html = `
        <div class="candidate-card" style="border-top-color: ${colorPartido}">
            <div class="card-header-flex">
                <div class="avatar-initials" style="color: ${colorPartido}; background-color: ${colorPartido}20; padding: 0; overflow: hidden; display: flex; align-items: center; justify-content: center; font-size: 24px;">
                    ${fotoPerfil}
                </div>
                <div class="card-info">
                    <div class="card-name">${candidato.nombre || 'Desconocido'}</div>
                    <div class="card-current-party" title="${pActual}">Postula por: ${pActualCorto} <br> <span style="font-size:11px; color:#888;">${cargosLabel ? `(${cargosLabel})` : ''}</span></div>
                </div>
            </div>
            
            <div class="histories-container">
                <div class="history-section">
                    <div class="history-title">Postulaciones (Orden cronológico)</div>
                    <div class="jersey-track">${camElectorales}</div>
                </div>
            </div>

            <div style="margin-top: 15px; padding-top: 12px; border-top: 1px dashed #ddd; font-size: 13px; text-align: center; color: #444; font-weight: bold;">
                Este candidato tuvo ${totalCamisetas} camiseta(s) política(s).
            </div>
        </div>
    `;
    container.innerHTML = html;
}





function setupBuscadorComparador(inputId, selectId, panelId, resultId) {
    const input = document.getElementById(inputId);
    const select = document.getElementById(selectId);
    const panel = document.getElementById(panelId);
    let timeout;

    if(!input || !select || !panel) return;

    const ejecutarBusqueda = () => {
        const val = input.value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").trim();
        const partidoFiltro = select.value;
        
        if (!val || val.length < 3) {
            panel.style.display = "none";
            return;
        }

        const terminosBusqueda = val.split(/\s+/);

        clearTimeout(timeout);
        timeout = setTimeout(() => {
            const matches = todosLosCandidatos.filter(cand => {
                if(!cand.nombre) return false;
                const nom = cand.nombre.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
                
                const matchText = terminosBusqueda.every(termino => nom.includes(termino));
                const matchPartido = (partidoFiltro === "" || partidoFiltro === "ALL") ? true : cand.partidoActual === partidoFiltro;
                
                return matchText && matchPartido;
            }).slice(0, 15);

            if (matches.length > 0) {
                panel.style.display = "block";
                let html = '';
                matches.forEach(cand => {
                    let pActual = cand.partidoActual || "Indep.";
                    let fotoMini = cand.idFoto ? `<img src="${getUrlImagen(cand.idFoto)}" style="width:100%; height:100%; object-fit:cover; border-radius:50%; filter: grayscale(100%);" onerror="this.outerHTML='${getInitials(cand.nombre)}'"/>` : getInitials(cand.nombre);

                    html += `
                        <div class="preselector-item" data-id="${cand.dni}">
                            <div class="preselector-avatar" style="padding:0; overflow:hidden;">${fotoMini}</div>
                            <div class="preselector-info">
                                <div class="preselector-name">${cand.nombre}</div>
                            </div>
                            <div class="preselector-badge">${pActual}</div>
                        </div>
                    `;
                });
                panel.innerHTML = html;

                panel.querySelectorAll('.preselector-item').forEach(item => {
                    item.addEventListener('click', function() {
                        const dniSeleccionado = this.getAttribute('data-id');
                        const candidato = todosLosCandidatos.find(c => c.dni === dniSeleccionado);
                        input.value = ""; 
                        panel.style.display = "none";
                        renderTarjetaCandidato(candidato, resultId);
                    });
                });
            } else {
                panel.style.display = "block";
                panel.innerHTML = `<div style="padding: 15px; color: #888; font-size:13px;">No hay coincidencia.</div>`;
            }
        }, 300);
    };

    input.addEventListener('input', ejecutarBusqueda);
    select.addEventListener('change', ejecutarBusqueda); 

    document.addEventListener("click", function (e) {
        if (e.target !== input && e.target !== select && e.target !== panel && !panel.contains(e.target)) {
            panel.style.display = "none";
        }
    });
}

// ===============================================
// FASE 3: HEATMAP NATIVO CSS GRID
// ===============================================
function renderHeatmap(candidatos, partidoFiltro = "ALL") {
    const grid = document.getElementById('heatmap-grid');
    if (!grid) return;

    let pool = candidatos;
    if (partidoFiltro !== "ALL") pool = candidatos.filter(c => c.partidoActual === partidoFiltro);

    const matriz = Array(5).fill(0).map(() => Array(10).fill(null).map(() => ({ count: 0, ejemplos: [] })));
    
    pool.forEach(c => {
        let historialSeguro = ensureArray(c.historialElectoral);
        const totalParticipaciones = historialSeguro.length + 1; 
        
        // Calculamos las camisetas usando la lógica de clusters
        let uniqueParties = calcularCamisetasUnicas(c);
        
        let colIndex = Math.min(totalParticipaciones - 1, 9);
        let rowIndex;
        if (uniqueParties >= 5) rowIndex = 0;
        else if (uniqueParties === 4) rowIndex = 1;
        else if (uniqueParties === 3) rowIndex = 2;
        else if (uniqueParties === 2) rowIndex = 3;
        else rowIndex = 4;

        matriz[rowIndex][colIndex].count++;
        if (matriz[rowIndex][colIndex].ejemplos.length < 4) matriz[rowIndex][colIndex].ejemplos.push(c.nombre);
    });

    let localMaxDensity = 0;
    for (let r = 0; r < 5; r++) {
        for (let c = 0; c < 10; c++) {
            if (r === 4 && c === 0) continue; 
            if (matriz[r][c].count > localMaxDensity) localMaxDensity = matriz[r][c].count;
        }
    }
    if (localMaxDensity === 0) localMaxDensity = 1;

    let html = '';
    for (let r = 0; r < 5; r++) {
        for (let c = 0; c < 10; c++) { 
            const bucket = matriz[r][c];
            let bgColor = "#f4f6f8"; 
            let textColor = "#111111"; 
            
            if (bucket.count > 0) {
                let intensidad;
                if (r === 4 && c === 0) intensidad = 1.0; 
                else {
                    const ratio = Math.sqrt(bucket.count / localMaxDensity);
                    intensidad = 0.3 + (ratio * 0.7); 
                    if (intensidad > 1) intensidad = 1;
                }
                bgColor = `rgba(230, 57, 70, ${intensidad})`; 
            }

            let tooltipHtml = '';
            if (bucket.count > 0) {
                const labelIntentos = (c === 9) ? "10 a más postulaciones totales" : `${c + 1} postulación(es) en total`;
                const labelPartidos = (r === 0) ? "con 5 o más partidos" : `con ${5 - r} partido(s)`;
                
                tooltipHtml = `
                <div class="tooltip">
                    <strong style="color:#fff; font-size:12px; margin-bottom:2px;">${labelIntentos} <br> ${labelPartidos}</strong>
                    <hr style="border:0; border-top:1px solid #444; margin: 4px 0;">
                    <strong>${bucket.count} candidatos</strong>
                    <div style="margin-top:4px; font-size:11px; color:#ccc;">Ejemplos:</div>
                    ${bucket.ejemplos.map(e => `• ${e}`).join('<br>')}
                    ${bucket.count > 4 ? `<br><i style="color:#888;">...y ${bucket.count - 4} más</i>` : ''}
                </div>`;
            }

            html += `
                <div class="heatmap-cell" style="background-color: ${bgColor}; color: ${textColor}; font-weight: bold; border-radius: 4px; border: 1px solid rgba(0,0,0,0.05);">
                    ${bucket.count > 0 ? bucket.count : ''}
                    ${tooltipHtml}
                </div>
            `;
        }
    }
    grid.innerHTML = html;
}

// ===============================================
// FASE 4: TIMELINE 1D (Antigüedad de Afiliación)
// ===============================================
const FECHA_LIMITE = new Date(2024, 7, 12); 

const deadlinePlugin = {
    id: 'deadlinePlugin',
    afterDraw(chart) {
        const ctx = chart.ctx;
        const xAxis = chart.scales.x;
        const xPos = xAxis.getPixelForValue(FECHA_LIMITE.getTime()); 

        if (xPos >= chart.chartArea.left && xPos <= chart.chartArea.right) {
            ctx.save();
            ctx.beginPath();
            ctx.moveTo(xPos, chart.chartArea.top);
            ctx.lineTo(xPos, chart.chartArea.bottom);
            ctx.lineWidth = 2;
            ctx.strokeStyle = 'rgba(229, 57, 53, 0.9)'; 
            ctx.setLineDash([5, 5]);
            ctx.stroke();

            ctx.fillStyle = 'rgba(229, 57, 53, 1)';
            ctx.font = 'bold 11px Arial';
            ctx.fillText('12 JUL 2024', xPos - 75, chart.chartArea.top + 15);
            ctx.fillText('FECHA LIMITE PARA AFILIARSE PARA CANDIDATEAR', xPos - 100, chart.chartArea.top + 30);
            ctx.restore();
        }
    }
};
if (typeof Chart !== 'undefined') Chart.register(deadlinePlugin);


// ESTA ES LA FUNCIÓN CLAVE CORREGIDA 
function extractAffiliationTimestamp(candidato) {
    let historialSeguro = ensureArray(candidato.historialPartidario);
    if (historialSeguro.length === 0) return null;

    // Busca específicamente el registro con "anio": "Vigente"
    const activeAffiliation = historialSeguro.find(h => h.anio === "Vigente");
    
    if (activeAffiliation && activeAffiliation.fechaInicio) {
        const parts = activeAffiliation.fechaInicio.split('/');
        if (parts.length === 3) return new Date(parts[2], parts[1] - 1, parts[0]).getTime();
    }
    return null;
}

function getDiasAntiguedad(timestampAfiliacion) {
    const msPerDay = 1000 * 60 * 60 * 24;
    return Math.round((FECHA_LIMITE.getTime() - timestampAfiliacion) / msPerDay);
}

// ===============================================
// LÍNEA DE TIEMPO (TIMELINE) - BLINDADA
// ===============================================

// ===============================================
// LÍNEA DE TIEMPO (TIMELINE) - BÚSQUEDA INTELIGENTE EN JSON
// ===============================================

window.cacheLogosTimeline = window.cacheLogosTimeline || {};

function renderTimeline(candidatos, partidoFiltro = "ALL") {
    const canvas = document.getElementById('timeline-chart');
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (timelineChartInstance) timelineChartInstance.destroy();

    // --- NUEVO: BUSCADOR INTELIGENTE EN EL DICCIONARIO ---
    // Recorre todo el JSON buscando el "nombre" real, sin importar la llave
    const encontrarArchivoLogo = (nombreBuscado) => {
        if (!nombreBuscado || typeof diccionarioPartidos === 'undefined') return null;
        
        const nombreLimpio = nombreBuscado.trim().toUpperCase();
        
        for (const key in diccionarioPartidos) {
            const data = diccionarioPartidos[key];
            if (data && data.nombre && data.nombre.trim().toUpperCase() === nombreLimpio) {
                // Si encontró el partido y tiene un logo válido (no vacío)
                if (data.logo && data.logo.trim() !== "") {
                    return data.logo; 
                }
                return null; 
            }
        }
        return null; // Si termina de buscar y no encuentra nada
    };

    // --- MOTOR DE FECHAS ---
    const OBTENER_TIMESTAMP = (c) => {
        if (!c.historialPartidario || !Array.isArray(c.historialPartidario)) return null;
        let af = c.historialPartidario.find(h => h.partido === c.partidoActual);
        if (!af || !af.fechaInicio) return null;
        let p = af.fechaInicio.split(/[\/\-]/);
        if (p.length === 3) {
            let d = p[0].length === 4 ? new Date(p[0], p[1]-1, p[2]) : new Date(p[2], p[1]-1, p[0]);
            return isNaN(d.getTime()) ? null : d.getTime();
        }
        return null;
    };

    const minX = (partidoFiltro === "ALL") ? new Date(2020, 0, 1).getTime() : new Date(2000, 0, 1).getTime();
    const maxX = new Date(2025, 11, 31).getTime();

    let datasets = [];
    const dataPoints = [];
    const bgColors = [];

    // ==========================================
    // INYECTOR DE LOGOS EN VIVO 
    // ==========================================
    const inyectarLogoEnVivo = (context) => {
        if (!context.raw || !context.raw.partido) return 'circle';
        
        const nombrePartido = context.raw.partido;
        const nombreParaCache = nombrePartido.trim().toUpperCase();
        
        // 1. ¿Ya lo cargamos antes? Lo devuelve al instante
        if (window.cacheLogosTimeline[nombreParaCache] && window.cacheLogosTimeline[nombreParaCache].complete) {
            return window.cacheLogosTimeline[nombreParaCache];
        }
        
        // 2. Si no lo tenemos, usamos el Buscador Inteligente
        const archivoLogo = encontrarArchivoLogo(nombrePartido);
        
        if (archivoLogo) {
            if (!window.cacheLogosTimeline[nombreParaCache]) {
                const img = new Image();
                img.onload = () => { if (timelineChartInstance) timelineChartInstance.update(); };
                
                // Usamos la ruta correcta con tu función
                img.src = typeof getUrlImagen === 'function' ? getUrlImagen(archivoLogo) : `fotos/${archivoLogo}`;
                img.width = (partidoFiltro === "ALL") ? 24 : 16;
                img.height = (partidoFiltro === "ALL") ? 24 : 16;
                
                window.cacheLogosTimeline[nombreParaCache] = img; // Lo guardamos en memoria
            }
        }
        return 'circle'; // Dibuja círculo mientras carga o si no hay logo
    };

    // ==========================================
    // RECOLECCIÓN DE DATOS
    // ==========================================
    if (partidoFiltro === "ALL") {
        const partyStats = {};
        candidatos.forEach(c => {
            const ts = OBTENER_TIMESTAMP(c);
            if (ts) {
                const p = c.partidoActual || "INDEPENDIENTE";
                if (!partyStats[p]) partyStats[p] = { sum: 0, count: 0 };
                partyStats[p].sum += ts;
                partyStats[p].count++;
            }
        });

        const sorted = Object.keys(partyStats).sort((a,b) => (partyStats[a].sum/partyStats[a].count) - (partyStats[b].sum/partyStats[b].count));
        const yLevels = [-7, 7, -5, 5, -3, 3, -1, 1, 0, -6, 6, -4, 4, -2, 2];

        sorted.forEach((p, i) => {
            const avg = partyStats[p].sum / partyStats[p].count;
            dataPoints.push({ x: avg, y: yLevels[i % yLevels.length], partido: p, count: partyStats[p].count });
            bgColors.push((typeof CONFIG !== 'undefined' && CONFIG.colores.partidos[p]) ? CONFIG.colores.partidos[p] : "#95A5A6");
        });

        datasets.push({
            label: 'Promedio',
            data: dataPoints,
            backgroundColor: bgColors,
            borderColor: '#ffffff',
            borderWidth: 2,
            pointRadius: 14,
            pointHoverRadius: 16,
            pointStyle: inyectarLogoEnVivo 
        });
        
    } else {
        candidatos.filter(c => c.partidoActual === partidoFiltro).forEach(c => {
            const ts = OBTENER_TIMESTAMP(c);
            if (ts) {
                dataPoints.push({ x: ts, y: (Math.random() * 14) - 7, nombre: c.nombre, partido: partidoFiltro });
            }
        });

        let pColor = (typeof CONFIG !== 'undefined' && CONFIG.colores.partidos[partidoFiltro]) ? CONFIG.colores.partidos[partidoFiltro] : "#95A5A6";

        datasets.push({
            label: 'Afiliados',
            data: dataPoints,
            backgroundColor: pColor,
            borderColor: '#ffffff',
            borderWidth: 1.5,
            pointRadius: 7,       /* <--- Un poco más pequeño para que sean puntitos limpios */
            pointHoverRadius: 10,
            pointStyle: 'circle'  /* <--- AQUÍ ESTÁ LA CLAVE: Forzamos a que sean solo círculos */
        });
    }

    // ==========================================
    // RENDERIZADO
    // ==========================================
    timelineChartInstance = new Chart(ctx, {
        type: 'scatter',
        data: { datasets: datasets },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            animation: false,
            layout: { padding: { top: 30, right: 20, left: 20 } },
            plugins: {
                legend: { display: false },
                tooltip: {
                    backgroundColor: 'rgba(17,17,17,0.95)',
                    callbacks: {
                        label: (ctx) => {
                            const d = ctx.raw;
                            const f = new Date(d.x).toLocaleDateString('es-PE', { year:'numeric', month:'short', day:'numeric'});
                            return partidoFiltro === "ALL" ? [`${d.partido}`, `Promedio: ${f}`, `Casos: ${d.count}`] : [`${d.nombre}`, `Afiliación: ${f}`];
                        }
                    }
                }
            },
            scales: {
                x: { type: 'linear', min: minX, max: maxX, ticks: { callback: v => new Date(v).getFullYear() } },
                y: { display: false, min: -10, max: 10 }
            }
        }
    });
}



// ===============================================
// RANKING DE PERDEDORES (SIN VICTORIAS)
// ===============================================
function renderRankingPerdedores(candidatos) {
    const container = document.getElementById('ranking-perdedores-container');
    if(!container) return;

    // --- BUSCADOR INTELIGENTE DE LOGOS ---
    const encontrarArchivoLogo = (nombreBuscado) => {
        if (!nombreBuscado || typeof diccionarioPartidos === 'undefined') return null;
        const nombreLimpio = nombreBuscado.trim().toUpperCase();
        for (const key in diccionarioPartidos) {
            const data = diccionarioPartidos[key];
            if (data && data.nombre && data.nombre.trim().toUpperCase() === nombreLimpio) {
                if (data.logo && data.logo.trim() !== "") return data.logo; 
            }
        }
        return null;
    };

    // 1. Encontrar a los que nunca ganaron
    let perdedores = candidatos.filter(c => {
        let historial = c.historialElectoral;
        if(!historial || !Array.isArray(historial) || historial.length === 0) return false; 
        
        let victorias = historial.filter(h => h.elegido && h.elegido.toUpperCase().trim() === 'SI').length;
        return victorias === 0;
    });

    // 2. Contar todas sus postulaciones
    let perdedoresMapeados = perdedores.map(c => {
        let totalPostulaciones = c.historialElectoral.length;
        return { ...c, totalPostulaciones };
    });

    // 3. Ordenar de mayor a menor derrotas y sacar el Top 5
    perdedoresMapeados.sort((a, b) => b.totalPostulaciones - a.totalPostulaciones);
    let topPerdedores = perdedoresMapeados.slice(0, 5);

    // 4. Invertir visualmente (el más perdedor a la derecha)
    topPerdedores.reverse();

    // 5. Generar el HTML
    let html = '';
    topPerdedores.forEach(c => {
        let pActual = c.partidoActual || "INDEPENDIENTE";
        let colorPartido = (typeof CONFIG !== 'undefined' && CONFIG.colores.partidos[pActual]) ? CONFIG.colores.partidos[pActual] : "#95A5A6";
        
        // Foto del candidato
        let iniciales = c.nombre ? c.nombre.substring(0, 2).toUpperCase() : "XX";
        let fotoHtml = c.idFoto ? 
            `<img src="${typeof getUrlImagen === 'function' ? getUrlImagen(c.idFoto) : `fotos/${c.idFoto}`}" class="loser-avatar" onerror="this.outerHTML='<div class=\\'loser-avatar\\' style=\\'color:${colorPartido};\\'>${iniciales}</div>'"/>` : 
            `<div class="loser-avatar" style="color:${colorPartido};">${iniciales}</div>`;

        // Logo del partido (Búsqueda inteligente)
        let archivoLogo = encontrarArchivoLogo(pActual);
        let logoHtml = '';
        
        if (archivoLogo) {
            let logoUrl = typeof getUrlImagen === 'function' ? getUrlImagen(archivoLogo) : `fotos/${archivoLogo}`;
            // Si hay logo, lo ponemos como imagen dentro del círculo
            logoHtml = `<img src="${logoUrl}" alt="${pActual}" style="width: 100%; height: 100%; object-fit: contain; border-radius: 50%; background-color: #fff;" onerror="this.style.display='none'"/>`;
        } else {
            // Si no hay logo (o es independiente), pintamos el fondo del color del partido
            logoHtml = `<div style="width: 100%; height: 100%; border-radius: 50%; background-color: ${colorPartido};"></div>`;
        }

        html += `
            <div class="loser-card" style="border-top: 3px solid ${colorPartido};">
                <div class="loser-party-circle" title="Postula por: ${pActual}" style="border-color: ${colorPartido}; background-color: #fff;">
                    ${logoHtml}
                </div>
                ${fotoHtml}
                <div class="loser-name">${c.nombre}</div>
                <div class="loser-stats">${c.totalPostulaciones} derrotas</div>
            </div>
        `;
    });

    container.innerHTML = html;
}